### ISSUE TITLE
Our tests with gzipped FITS files fail on Windows

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1269]
See this:

https://ci.appveyor.com/project/Cadair/sunpy/build/1.0.184#L680

and this:

https://groups.google.com/forum/#!topic/astropy-dev/1KybTXAPdqU

**Comment by ayshih** [comment]
So, this is a bug with `astropy.io.fits`?

**Comment by Cadair** [comment]
@ayshih It doesn't seem that way, in that it seems to be specific to out files, their tests do not fail (one assumes).

**Comment by ayshih** [comment]
Ah, the problem is sillier.  Two of our three test "files" – `gzip_test.fts.gz` and `gzip_test.fit.gz` – aren't actually files, but rather Unix-style links to the real file `gzip_test.fits.gz`, and of course that doesn't work on Windows.  I'm not sure we need to test all three extensions, but if we do, we just need to make those fake files into real files.

**Comment by Cadair** [comment]
@ayshih oh man I should have noticed that!!

**Comment by Cadair** [comment]
Should be fixed in the CI PR now.
