### ISSUE TITLE
JSOC download skips first file in Results object

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1357]

**Comment by gunner272** [comment]
@Cadair : could you please update the description

**Comment by dumindux** [comment]
Here a file is skipped because results.poke() is called at following line,
https://github.com/sunpy/sunpy/blob/master/sunpy/net/jsoc/jsoc.py#L427

vso.Results object keeps count of the downloads and poke() tells that a one download is finished. since in the above poke() is called earlier, Results object only keeps track of (real downloads-1) downloads. Because of this. Results.wait() method returns when only (real downloads-1)  completed. So it leaves out a download.
