### ISSUE TITLE
Database seems to be duplicating entries sometimes

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1369]
This test:
https://github.com/sunpy/sunpy/blob/master/sunpy%2Fdatabase%2Ftests%2Ftest_database.py#L790

Is failing, and I can't work out where the bug is, but it seems to be in the database rather than in the VSO, as the vso is returning two results.

**Comment by dumindux** [comment]
@Cadair It seems database module create multiple database entries(which are not duplicates) for the same file for each header in the fits file. In this case 2 entries for each file. That's why len(db) becomes 4. Here is the code responsible for creating an Entry for each header in the fits file.
https://github.com/sunpy/sunpy/blob/master/sunpy/database/tables.py#L468

I don't have a good understanding about fits file structure. But I think we shouldn't expect len(db) to be 2 here : ).

**Comment by Cadair** [comment]
@dumindux OH! Right yes of course, that makes sense. The reason this started failing is the change to the default download methods in #1360 as rice compressed extensions are separate and therefore have two HDUs.

Could you make a PR with the change from 2 to 4? Thanks

**Comment by dumindux** [comment]
@Cadair Hm right. I will make the PR.
