### ISSUE TITLE
warnings issued with XRT image display, metadata

### ISSUE THREAD

**Issue by jslavin** [sunpy/sunpy#1388]
While using sunpy to display an XRT image I get: several warnings:
Warning: This map is not aligned. Plot axes may be incorrect
(even though alignment looks good)
Warning: Missing metadata for solar radius: assuming photospheric limb as seen from Earth
What does sunpy want in terms of metadata?  I am the person maintaining/upgrading the Level 1 pipeline, so I could add more metadata if necessary
Warning: Missing metadata for Sun-spacecraft separation: assuming Sun-Earth distance
Warning: Missing metadata for heliographic latitude: assuming Earth-based observer
RuntimeWarning: invalid value encountered in sqrt
  z = np.sqrt(rsun_meters ** 2 - x ** 2 - y ** 2)

Again, it would be good to know what metadata is desired.  It may be possible to include that in future Level 1 data that is generated by the XRT pipeline.

Regards,
Jon

**Comment by Cadair** [comment]
Hello @jslavin thanks for opening an issue.

To explain the warnings:

> Warning: This map is not aligned. Plot axes may be incorrect

This is because the rotation information in the header (Any of CROTA2, PCi_j or CDi_j) are prescribing a rotation not equal to 0, and therefore there is a slight offset between the plot axes and the HPC coordinate system described by the header.

If you run `mymap.rotate()` first, it will perform an affine transform on the image to align the solar N-S line with the y axis.

> Warning: Missing metadata for solar radius: assuming photospheric limb as seen from Earth

This is because there is no information in the header with the keys `'rsun_obs' `or `'solar_r'`. See (https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L310) If you don't have this info in your header it can be added, if you do have it but with a different key we can add that to the XRT source.

> Warning: Missing metadata for Sun-spacecraft separation: assuming Sun-Earth distance

This is the same kind of deal, you need `'dsun_obs'` (See: https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L243)

> Warning: Missing metadata for heliographic latitude: assuming Earth-based observer

This time it's `'crln_obs'` (https://github.com/sunpy/sunpy/blob/master/sunpy/map/mapbase.py#L330).

Hope this helps.
Stuart

**Comment by jslavin** [comment]
Hi Stuart,

Thanks for the explanations. In the meantime since I posted that message, I
looked at the source code a bit.  I got the dsun_obs and rsun_obs, but it
looks to me like the last one is one of hglt_obs, crlt_obs or solar_b0.
I'll look into getting some or all of these keywords into the Level 1
headers.

Jon
