### ISSUE TITLE
Make net modules consistent in the action verbs they use

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1703]
Fido uses `search` and `fetch` and vso uses `query` and `get`. Let's be consistent.

**Comment by Cadair** [comment]
I think on balance I prefer changing Fido to `get` and `query`.

@sunpy/sunpy-developers any more opinions?

**Comment by wafels** [comment]
Any particular reason?  The best reason I see for `query` and `get` is that these will require the minimum number of changes to the code.

**Comment by Cadair** [comment]
@wafels that and people used to the current API wont have to change. Also I can see no advantage to changing, unless someone has an argument to make there?

**Comment by ayshih** [comment]
Well, ignoring the inertia of history, my perspectives are:
* `fetch` is better than `get` because the word "fetch" is less common than the too-generic "get" so better captures the weight of the download operation.  Plus, "fetch" works excellently with the dog metaphor.
* `search` is better than `query` because "search" is a more natural word to use than the jargon-ish "query".  "Search" also works decently with the dog metaphor; dogs don't query!

**Comment by Cadair** [comment]
Your arguments are reasonable, but are they worth changing all the existing code?

**Comment by dpshelio** [comment]
I think I'm with @ayshih - but I also find annoying to have to change something which... in principle we are not going to suggest to use.  I would propose to keep everything as it is for the merging, then create wrappers around the old API for deprecation while converting them to the new verbs. So that gives us a bit of extra time (or someone during the conference in a couple of weeks wants to help).

**Comment by nabobalis** [comment]
Would it not be a straightforward find and replace?

**Comment by Cadair** [comment]
@nabobalis yeah, but we would want to keep functionality in the VSO JSOC HEK HELIO etc clients for at least one release. So we would have to wrap and deprecate.

**Comment by ehsteve** [comment]
I agree with @ayshih and suggest we implement @Cadair last suggestion.

**Comment by Cadair** [comment]
@sunpy/sunpy-developers I can't see me getting time to do this in the next 6 days as well as the documentaion work. I would really like this in 0.8 (because of all the deprecations) so I will actually post stickers to someone who patches this by the dev meeting next week.

**Comment by nabobalis** [comment]
@Cadair What doc changes?
