### ISSUE TITLE
show_colormaps() should check how much display room is available

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#1781]
It can generate plots which are larger than my screen so I cannot see all of the colormaps.

**Comment by larrymanley** [comment]
Is there a mechanism in matplotlib for that?  Perhaps use a figure with explicit values for size and dpi.  Otherwise, even on a similar screen, the figure could display differently if the user has different defaults specified in .matplotlibrc.  Should also remove the live x,y values at the bottom of the plot window.

**Comment by larrymanley** [comment]
The figure size is set as 5,10 on line 183 of cm.py, just add dpi=___.  64 dpi is conservative and the window can be resized.

**Comment by abit2** [comment]
@ehsteve https://github.com/sunpy/sunpy/pull/1895 please review new here

**Comment by abit2** [comment]
https://github.com/sunpy/sunpy/pull/1901
@dpshelio 
thanks for helping me :smile:

**Comment by prateekiiest** [comment]
Pls review #1980
