### ISSUE TITLE
List of accepted metadata for custom SunPy Maps

### ISSUE THREAD

**Issue by aringlis** [sunpy/sunpy#1832]
When creating custom SunPy maps (i.e. from a 2D array), there is no obvious way to see what the accepted metadata keywords are. I have been rooting around in mapbase.py to try and find the expected input. 

For user-friendliness, it would be nice to have a full list of the metadata keywords that can be input.

**Comment by Cadair** [comment]
I agree, it will change dependant upon the instrument, but for the moment we should at least document the defaults in `GenericMap`

**Comment by dpshelio** [comment]
we could have it interactively in the way `iraf` used to work :)

**Comment by Cadair** [comment]
I have no idea what that is.

**Comment by Cadair** [comment]
what is that?

**Comment by dpshelio** [comment]
@Cadair you don't need to look back to `iraf`, but in short, it opened a text-like editor with the fields to write them in, and then generated the object based on these things. It was kind of ncurses but based on vi.

**Comment by Alex-Ian-Hamilton** [comment]
From my investigations, with metadata in a dictionary called meta, I needed to add the following values.

For WCS, HMI has typical values:
    meta['cdelt1'] = 0.504219
    meta['cdelt2'] = 0.504219
    meta['cunit1'] = 'arcsec'
    meta['cunit2'] = 'arcsec'
    meta['dsun_obs'] = 147141258270.0 # Else Warning: Missing metadata for Sun-spacecraft separation
    meta['crpix1'] = 2045.131592
    meta['crpix2'] = 2042.132812
    meta['crval1'] = 0.0
    meta['crval2'] = 0.0

    For non-earth observations you need:
    meta['HGLN_OBS'] = 70.438797
    meta['HGLT_OBS'] = -4.521303

    Which HMI actually stores as:
    meta['crln_obs'] = 70.438797
    meta['crlt_obs'] = -4.521303

For a observation time:
dic_meta['DATE_OBS'] = '2011-02-15T00:58:57.30'

To be recognised as an SDO HMI map you need:    
    dic_meta['telescop'] = 'SDO/HMI'
    dic_meta['instrume'] = 'HMI' # generally 'HMI_FRONT2', but only checks using .startswith.
    dic_meta['content'] = 'MAGNETOGRAM'

If all the above are give, plots get generated without warnings and you can make a map sequence plot work (that's temperamental otherwise).
I can dig around the source to look for alternatives if people thing there are some.

**Comment by wtbarnes** [comment]
Doesn't #3083 solve this?

**Comment by Cadair** [comment]
I would agree that it does.
