### ISSUE TITLE
timeout: timed out while querying SDO data

### ISSUE THREAD

**Issue by azakhtyamov** [sunpy/sunpy#1911]
Hello!

client = VSOClient()
query_response = client.query_legacy(tstart='2013/12/06 00:00:00', tend='2013/12/06 00:05:00', instrument='AIA')

End up with timeout: timed out error.

However, 
query_response = client.query_legacy(tstart='2013/12/06 00:00:00', tend='2013/12/06 00:05:00', instrument='EAE') 
works just fine. 

Any thoughts?

**Comment by Cadair** [comment]
I just encountered this, it seems that the HMI/AIA backend (JSOC) for the VSO is having issues. I do not believe this is a SunPy bug. Have you tried the VSO web interface?

**Comment by azakhtyamov** [comment]
Yes, VSO web interface is working as it should.

**Comment by wtbarnes** [comment]
I've had trouble querying HMI data in the past 24 hours as well, i.e. queries that I know should return several fits files are now returning nothing.

**Comment by Cadair** [comment]
yes, likewise, it must be a server side issue but I don't know if we can mitigate it.

**Comment by jhourcle** [comment]
This is very likely due to the cutover to HTTPS that NASA forced on us.  (and cut out 3 months of the deadline ... which we found out 3 weeks before the new deadline).

(and it's not like I didn't say something about this -- which the GSA folks deleted all of, so there's no obvious record of it : https://web.archive.org/web/20150420100055/https://github.com/WhiteHouse/https/issues/107 )

I've had to roll quite a few of the data providers back to HTTP due to issues w/ a broken chain of trust making the VSO core service refuse to talk to them.  I'll do the same for this one, and let the others know that things are broken worse than we realized.

**Comment by jhourcle** [comment]
I've rolled the VSO registry entries back to using HTTP.  This is just a temporary fix while we figure out what the real problem is.  NSO (which SunPy uses as their main API endpoint) will update on the hour (in about 10 minutes).

**Comment by Cadair** [comment]
This should hopefully be fixed on the VSO side now.

**Comment by azakhtyamov** [comment]
Thanks everyone for help. Now it works fine!
