### ISSUE TITLE
Online Build is Failing due to a RHESSI VSO Search

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#1973]
This query is no longer returning results: 

```python
from sunpy.net import Fido, attrs as a

Fido.search(a.Time((2011, 9, 20, 1), (2011, 9, 20, 2)), a.Instrument('RHESSI'))
```

**Comment by jhourcle** [comment]
The problem is on the VSO side of things.  The RHESSI folks started redirecting HTTP to HTTPS, and our attempts to retrieve their catalog files are failing.  Here's what I get when I try connecting w/ debugging, using the same libraries that the failing code uses:

bash-3.2$ perl5.12 /tmp/test.pl 'https://hesperia.gsfc.nasa.gov/hessidata/dbase/hsi_filedb_201106.txt'
DEBUG: .../IO/Socket/SSL.pm:2524: new ctx 140406175911664
DEBUG: .../IO/Socket/SSL.pm:526: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:528: socket connected
DEBUG: .../IO/Socket/SSL.pm:550: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:592: not using SNI because openssl is too old
DEBUG: .../IO/Socket/SSL.pm:634: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:647: Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:657: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:667: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:687: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:647: Net::SSLeay::connect -> 0
DEBUG: .../IO/Socket/SSL.pm:695: connection failed - connect returned 0
DEBUG: .../IO/Socket/SSL.pm:1763: SSL connect attempt failed because of handshake problems
DEBUG: .../IO/Socket/SSL.pm:1747: IO::Socket::INET6 configuration failed
DEBUG: .../IO/Socket/SSL.pm:2557: free ctx 140406175911664 open=140406175911664
DEBUG: .../IO/Socket/SSL.pm:2562: free ctx 140406175911664 callback
DEBUG: .../IO/Socket/SSL.pm:2569: OK free ctx 140406175911664

**Comment by jhourcle** [comment]
doh.  Looks like the module got installed w/ the OS supplied openssl

**Comment by Cadair** [comment]
ahhh openssl.

**Comment by jhourcle** [comment]
I gave up on trying to get the HTTPS stuff happy (had to try to match compilers w/ the version of perl that we were using ... with no luck, as we didn't build it here).  So I found where they had it available via FTP.

**Comment by Cadair** [comment]
Thanks!
