### ISSUE TITLE
Change the default keys for jsoc search results to be T_REC rather than DATE and T_OBS

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2584]
This is as simple as changing [this](https://github.com/sunpy/sunpy/blob/master/sunpy/net/jsoc/jsoc.py#L843) line to read:
```python
['T_REC', 'TELESCOP', 'INSTRUME', 'WAVELNTH']
```
Unless @mbobra has a better idea.

**Comment by mbobra** [comment]
I'm fine with this, @Cadair. `T_REC` is a prime key for most DRMS series, so it is a good choice. If you're willing to expand this set to 5 keywords, instead of 4, I suggest you add `CAR_ROT`. Most people who use SunPy understand Carrington rotation numbers and some of the HMI synoptic data are indexed by `CAR_ROT`.
