### ISSUE TITLE
Sample AIA images in the gallery do not show SunPy plotting very well

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2590]
The colors selected AIA images in the gallery are badly scaled.  This is probably because the data contain one or two very bright pixels which is throwing the existing scaling off.

Users going to the gallery are seeing badly scaled images, and that's not a good advertisement for SunPy.  Either the images should be changed, the default AIA scaling should be changed, or some clipping of the intensity scale should be included in the example gallery code as appropriate.

**Comment by sapnamish** [comment]
I want to work on this issue

**Comment by nabobalis** [comment]
@sapnamish You don't need to ask for permission to work on this issue! You can go right ahead!

**Comment by ravindra1307** [comment]
is this issue still open ? i want to work on this issue. can you please guide me to the page where i can see badly scaled image ?

**Comment by nabobalis** [comment]
Hi @ravindra1307, yes this issue is still open. I assume that @wafels is referring to the `Sample Data Set Overview` gallery example. But also to a more general point that we use the sample data in many of our examples and the scaling of the AIA images might need to be looked at either within the examples or inside the AIA Map code.

**Comment by Cadair** [comment]
now that #3100 is merged we should modify the examples and the docs where appropriate to use that functionality to show the images with better scaling.
