### ISSUE TITLE
Submap differential derotation has incorrect CRVAL1, CRVAL2 calculation

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#2600]
The differential map derotation updates CRVAL1, CRVAL2 by solar-rotating the existing CRVAL1, CRVAL2 values. The position (CRVAL1, CRVAL2) is the position of the reference pixel in world units.  This position need not be in the FOV of the submap, and so the rotation applied can be incorrect - it has nothing to do with the actual piece of Sun being rotated. A fix for this will be implemented in #2596.  A solution is to update CRVAL1, CRVAL2 with the amount that the center of the field of view in the submap has moved due to solar differential rotation.

**Comment by wafels** [comment]
Yes, the significant changes are here:

https://github.com/wafels/sunpy/blob/mapcube_solar_differential_derotate/sunpy/physics/differential_rotation.py#L320

My problem is that I should have made this fix first, and then gone on to
do the inclusion of mapcube differential rotation in another PR.  The
classic mistakes of (a) thinking it would be easy and (b) not having enough
time to do the whole thing.

Let me make another PR that just fixes #2600.

**Comment by wtbarnes** [comment]
Ah Ok. So if I understand this correctly, your proposed fix should allow for differential rotation to be applied to submaps?

**Comment by wafels** [comment]
Differential rotation can already be applied to submaps.  The issue is that
the current code does not properly change the CRVAL1 and CRVAL2 values in
the meta output.  The PR ensures CRVAL1 and CRVAL2 are set to the correct
values.

**Comment by wtbarnes** [comment]
Sure I get that. What I'm aiming to do is rotate, then create a submap following the rotation. If I understand correctly, with your PR, there should be no difference between these two operations:

* First rotate, then submap
* First submap, then rotate

(Other than the obvious lack of pixels to rotate into the map if we take the submap first) whereas before the second option would give an incorrectly oriented map because the `diff_rot` function did not update `crval1` and `crval2`. 

However, I found that the two do not give the same results (even with your PR). I'm probably just missing something here. Below is an example of what I'm talking about.

## Rotate then Crop
```python

import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
from sunpy.map import Map
from astropy.coordinates import SkyCoord
from sunpy.physics.differential_rotation import diffrot_map,solar_rotate_coordinate
import sunpy.data.sample

m = Map(sunpy.data.sample.AIA_171_IMAGE)
# First rotate
m_rotate = diffrot_map(m,dt=12*u.hour,rot_type='snodgrass')
# Then crop
lc = u.Quantity([-250,0],'arcsec')
rc = u.Quantity([250,500],'arcsec')
m_rotate_crop = m_rotate.submap(
    SkyCoord(*lc,frame=m_rotate.coordinate_frame),
    SkyCoord(*rc,frame=m_rotate.coordinate_frame)
)
```

## Crop then Rotate
```python
# First crop
m_crop = m.submap(
    SkyCoord(*lc,frame=m.coordinate_frame),
    SkyCoord(*rc,frame=m.coordinate_frame)
)
# Then rotate
m_crop_rotate = diffrot_map(m_crop,dt=12*u.hour,rot_type='snodgrass')
# Wafels fix here
new_meta = m_crop_rotate.meta.copy()
rot_center = solar_rotate_coordinate(m_crop.center,m_crop_rotate.date,rot_type='snodgrass')
new_meta['crval1'] = m_crop.reference_coordinate.Tx.value + (m_crop.center.Tx.value - rot_center.Tx.value)
new_meta['crval2'] = m_crop.reference_coordinate.Ty.value + (m_crop.center.Ty.value - rot_center.Ty.value)
m_crop_rotate = Map(m_crop_rotate.data, new_meta)
```
The map that was cropped and then rotated seems to not have been rotated at all as far as the coordinates are concerned. I'm not sure what is going on here. Maybe I'm missing something obvious.

![image](https://user-images.githubusercontent.com/8676141/40955976-42da36de-6853-11e8-815d-369646de1402.png)

**Comment by dpshelio** [comment]
Interesting result you've got there.  I wonder if I've messed up with some sign when moving the coordinates. Though I'm pretty sure I compared it with ssw... Anyway, @wtbarnes you seem to be using it right, but the code must be wrong.
The advantage of using rotating the submaps is that the memory used is less.

**Comment by wtbarnes** [comment]
@dpshelio Yeah that's why I'm wanting to submap first. Doing a the diff rotate on the full map is too slow for what I'm wanting to do. 

If I don't include @wafels fix for the `crval` metadata, in the crop-rotate case, the map coordinates seem to get "over rotated." This is shown in the plot below (where I've included some padding around the maps to show the rotation a bit better).

![image](https://user-images.githubusercontent.com/8676141/41067407-189bb920-69ab-11e8-9257-6af802613d14.png)

**Comment by Cadair** [comment]
it appears that when it's a submap it's cropping the data on the right hand side of the submap when it shouldn't be?

**Comment by wtbarnes** [comment]
@Cadair Which case are you referring to?
