### ISSUE TITLE
useless warnings caused by meta data values in hinode.py

### ISSUE THREAD

**Issue by jslavin** [sunpy/sunpy#2609]
Hi,

When making plots (maps) of Hinode XRT data I get warnings about two things 1) a deprecation warning regarding setting colormaps and 2) a warning about missing data on heliographic longitude. The first can easily be fixed by replacing
self.plot_settings['cmap'] = cm.get_cmap(name='hinodexrt')
with
self.plot_settings['cmap'] = plt.get_cmap(name='hinodexrt')
with an 'import matplotlib.pyplot as plt' also. I assume that such changes are intended anyways given that the deprecation warning was created.
The second one can be avoided by
self.meta['hgln_obs'] = 0.0
since there is not now, nor will there, be any data on the observer's heliographic longitude in XRT data files.
Neither of these warnings is useful, so these changes avoid those nuisance warnings.

**Comment by wafels** [comment]
So the first issue noted above is being tracked in #2616.

Looking at the other source map files, I think there is a case to be made to fix the value of hgln_obs there in the XRT source file.  We fix different aspects from different instruments in the source files in order to make them usable by Map, notably the SOHO-Sun distance.  I say there is a case to fix the value of hgln_obs for XRT based on the fact we fix the SOHO-Sun distance.

**Comment by Cadair** [comment]
@wafels When you say "fix" do you mean inject 0 as the value in the header?

The idea of the warning is that it's informational to inform the user that we are assuming `meta['hgln_obs'] = 0.0` because it's not present in the header. A user who understands that for Hinode this is a sensible assumption is safe to ignore it. If you got this warning while loading in STEREO data you might want to be a little more concerned.

On the other hand, I appreciate the fact that SunPy dosen't handle its warnings as well as it could so people probably just end up ignoring all of them.

**Comment by jslavin** [comment]
To reinforce what Stuart said, there are no plans at this point to add any
data on the heliographic longitude of the spacecraft to the XRT data file
headers. Doing so in a way that adds information would require figuring out
a way to get the spacecraft location.  Even adding a value of 0 to the
header would require changing the headers on the entire database, which
would take a significant amount of time.  Not impossible, but not very
useful either.  So I'd advocate for simply setting self.meta['hgln_obs'] =
0.0 for XRT data, as I said in my earlier post.

Jon

**Comment by wafels** [comment]
We silently fix (as in add a key-value pair to the meta property) the
distance of the Sun from SOHO silently, so why not do the same with
Hinode?  Or maybe we should raise a warning when we fix something for
SOHO.  All I was suggesting is that we have a precedent for silently making
source-dependent fixes to FITS file meta data as handled by SunPy.  Maybe
silent is bad, and we should always raise a warning when making an
assumption about any part of the file meta data.

**Comment by jslavin** [comment]
Hi Jack,

Since hinode.py is Hinode specific I don't see anything wrong with silently
fixing missing meta data for values that we know will never be there.
Otherwise one is always getting useless warnings, which would tend to lead
to ignoring warnings generally (besides being annoying).  I think fixing
the value of meta['hgln'] in the __init__ method of XRTMap is a good
approach. Is that what you mean by "silently fix"?

Jon

**Comment by wafels** [comment]
Yes - setting the value of meta['hgln'] in the __init__ method of XRTMap is
what I mean.    Or we raise warnings when we set the Sun-Earth distance in
EIT and LASCO maps.  Either would be consistent.  At the moment there is no
consistency.

Also, I thought the purpose of the source files was to take care of
instrument idiosyncrasies such as the two above?  Wouldn't an explicit
comment in the code be enough to inform the user what is going on with
regard to XRT FITS files?

**Comment by dpshelio** [comment]
My 2 cents for this issue from last year:

I am not in favour of not showing warnings when we are hardcoding values that shouldn't be there. If a person who is not familiar with Hinode/XRT believes what sunpy says because we don't show the error is bad. Since the warning should only appear once per session, I don't think it's bad to show it (or it's not? ipython/ipython#11207).

My other opinion of why we should tell the people of these warnings is because by not doing so people may have a chance to tell the new instruments that their data should be good.

**Comment by dstansby** [comment]
I think the first original issue is now fixed, and the second warning is a reasonable warning given sunpy is making assumptions about the data. I'm going to close this, but if there are still issues with spurious warnings feel free to leave a comment here or open a new issue.
