### ISSUE TITLE
Figure tests directory gets wiped after running via the test runner.

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#2653]
Just discovered that when I run:
```bash
python setup.py test --figure-only
```
The resulting figure images are saved in a tmp directory that gets wiped at the end of the process (this is under linux for me)

Using `pytest` adds the folder into my sunpy folder.

**Comment by Cadair** [comment]
@dstansby fyi

**Comment by dstansby** [comment]
Are you running that from a clean copy of the master branch? And do you get the same behaviour running `python setup.py test` (without the figure only flag)?

**Comment by nabobalis** [comment]
Yeah, so I think the test runner called via `setup.py` dumps the files into `/tmp/<some folder>` and once its done it cleans it up.

**Comment by dstansby** [comment]
So it's possible to access the temporary test directory using `os.getcwd()`, but I have no idea to access the directory from which `python setup.py test` is run, to move the files there. Any ideas @Cadair? (yet again I am baffled by the whole `python setup.py test` business)

**Comment by Cadair** [comment]
The only solution I can think of is to enable passing a base directory as a CLI argument to `py.test` because then the test command could just pass the correct dir to the pytest instance. I can not think of another way of letting pytest know where it should save the files.

**Comment by dstansby** [comment]
So, the problem is that

- `python setup.py test` calls some code in `astropy_helpers`...
- ... which then calls some other code in `astropy`...
- ... which then creates a shell command, which is run using `subprocess` from a temp directory...
- ... so the original directory from which `setup.py` test was called from isn't visible to any tests that are run...
- ... which means it's basically impossible to extract the figures from the temp directory to the current working directory.

Previously this was got round by creating another temp dir, saving the figures to that, and just printing it to stdout after the tests. Options:

- We could revert to that, but I think it's a massive faff having to try and open that temp dir just to view the generated images.
- We could try and change something upstream (in `astropy`) to make extracting images from the tests easier
- We could drop `python setup.py test` in favor of `pytest` (which has downsides, but would be easiest for me to implement on the circleCI tests in the short term)

Thoughts?

**Comment by Cadair** [comment]
@dstansby your code path analysis matches my understanding, the `setup.py test` command builds arguments for and then runs `sunpy.self_test` [here](https://github.com/sunpy/sunpy/blob/master/sunpy/tests/setup_command.py#L60).

So if we can add an optional parameter to the sunpy test runner that is the base directory for the figures i.e. defaults to `./` we can have `setup.py test` pass the base directory in which it was run to `sunpy.self_test`.

**Comment by Cadair** [comment]
oh wait, I missed a step, `sunpy.self_test` calls `pytest.main` which means that we need to add a cli argument to pytest to make it all the way through the stack.

**Comment by Cadair** [comment]
I think I am close to a solution on this.
