### ISSUE TITLE
TimeSeries having trouble with 'None' unit type.

### ISSUE THREAD

**Issue by abotiamnot** [sunpy/sunpy#2657]
In TimeSeries, if there is an OrderedDict key with the value None, it ignores all the other keys and their respective values in the OrderedDict. I think TimeSeries should give some sort of warning, like it does when no unit is assigned to a column.

![image](https://user-images.githubusercontent.com/36379971/41436583-c19e7748-703f-11e8-9f68-30b101a4992f.png)

```
import pandas as pd
from collections import OrderedDict
import astropy.units as u
d = pd.DataFrame({'x': [1, 2], 'y': [3, 4]})
units = OrderedDict([('x', u.km), ('y', None)])
ts_ = ts.TimeSeries(d, units)
```

**Comment by dstansby** [comment]
Could you post a simple self contained example that reproduces this (including module imports)? It looks like you have an example in the screenshot, but it's easier to have it formatted as code in a comment for copy/pasting.

**Comment by abotiamnot** [comment]
I've just added the code to reproduce this problem.

**Comment by Alex-Ian-Hamilton** [comment]
This problem is that you have an invalid input to the units ordered dictionary.
You are using a None (NoneType) and not an AstrtrPy Unit (or Quantity), and that is (IMO) quite far from correct usage of the TimeSeries units dictionary.
You code would work if you either applied an explicit dimensionless AstroPy unit:
`units = OrderedDict([('x', u.km), ('y', u.dimensionless_unscaled)])`
Or simply omit the y units altogether:
`units = OrderedDict([('x', u.km)])`
In which case TimeSeries implicitly assumes it's dimensionless, while giving a user warning...
Tho having said that, the warning string has a bug in it! :/
warnings.warn("Unknown units for \""+str(column)+"\"", Warning

So the questions are, is that fine and excepted behaviour and/or should we add a warning either way?
I personally think a warning is worthwhile, and being a bit more explicit in the description in the docs so people don't make this mistake.

**Comment by dstansby** [comment]
This seems to be fine now; the following code prints what I would expect:
```python
from sunpy.timeseries import GenericTimeSeries
from sunpy.time import parse_time
from astropy.time import TimeDelta
import astropy.units as u
import numpy as np
import pandas as pd
times = parse_time("now") - TimeDelta(np.arange(24 * 60)*u.minute)
data = np.random.rand(24 * 60, 2)

df = pd.DataFrame(data, index=times, columns=['col1', 'col2'])
ts = GenericTimeSeries(df, units={'col1': None, 'col2': u.km})
print(ts.quantity('col1'))
print(ts.quantity('col2'))
```
