### ISSUE TITLE
Support as input, and use pathlib everwhere

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2822]
We should use pathlib now we are Python 3 only. We should make sure all the functions that take path-like inputs accept `Path` objects as well as using pathlib in places like `map.Map` to standardise out slashes over platforms and other quirks of paths.

First attempt at changing test files: #2891

If you plan to undertake this, the best suggestion is to focus on a submodule, one at a time and send that as a pull request.

**Comment by jains8844** [comment]
For the mentioned issue, I have made a certain changes to the following files : 

1. sunpy/map/map_factory.py
https://github.com/jains8844/Contri-to-Issues/blob/master/map_factory.py
2. sunpy/io/file_tools.py
https://github.com/jains8844/Contri-to-Issues/blob/master/file_tools.py
3. sunpy/io/ana.py
https://github.com/jains8844/Contri-to-Issues/blob/master/ana.py
4. sunpy/io/jp2.py
https://github.com/jains8844/Contri-to-Issues/blob/master/jp2.py
5. sunpy/io/fits.py
https://github.com/jains8844/Contri-to-Issues/blob/master/fits.py

These changes would make the reading of headers and data from maps in certain directories to be completely based on pathlib rather than os module and will be working on pathlib objects in place of strings. Whenever string path is needed to be passed, the object can be converted into string else it remains as an object only.
I have not yet worked in writing data to files.

So kindly see if the changes done would work or not .

**Comment by nabobalis** [comment]
It would be easier to review any changes as a pull request. 

But one suggestion off the top is that we do not allow `from pathlib import *`. You will have to use `import pathlib` instead.

**Comment by jains8844** [comment]
Sure :+1:

**Comment by nabobalis** [comment]
Also you will need to fork the SunPy repo and then make those changes your fork, so you can then submit the pull request. I'm not sure we can take the code changes via another method.

**Comment by darthgera123** [comment]
can i work on this issue?

**Comment by nabobalis** [comment]
Sure

**Comment by darthgera123** [comment]
umm the required suggestions are already implemented in the mentioned files above

**Comment by nabobalis** [comment]
Those files are not in our repo.

**Comment by darthgera123** [comment]
so what exactly am i required to do? because the repo i forked & cloned had the suggestions implemented

**Comment by nabobalis** [comment]
What repo did you fork? I'm not aware that our repo (sunpy/sunpy) has pathlib support. 

While there is a pull request open that tries to add support. It has been untouched for a while now. You could start there.

**Comment by darthgera123** [comment]
i have forked this repo only. Could you please mention the PR please, so that i could start

**Comment by nabobalis** [comment]
While we might have pathlib imported in places I'm relatively sure we don't support it or use it internally.

The pull request is: https://github.com/sunpy/sunpy/pull/2828

I would recommend having a read of the pathlib documentation before you start so you can get familiar with it.

**Comment by darthgera123** [comment]
sorry for replying so late but do you want me to refactor all such files in a way where we replace os.pathlib with functions from pathlib module right? Please reply

**Comment by darthgera123** [comment]
created a pull request please review. Ill finish the work accordingly

**Comment by dstansby** [comment]
I think this is now fixed?

**Comment by dstansby** [comment]
Since there were no objections, I'm going to close this

**Comment by nabobalis** [comment]
I don't think any work was ever merged for this.

**Comment by dstansby** [comment]
Pretty sure it works now in map_factory, but actually doesn't look like it does in TimeSeries yet

**Comment by bhadreshpsavani** [comment]
Shall I work on it?

**Comment by dstansby** [comment]
Closed by https://github.com/sunpy/sunpy/pull/4589 I think? If anyone can find anywhere else that should take a `Path` as input feel free to comment or reopen.
