### ISSUE TITLE
VSO to return results only based on a time query

### ISSUE THREAD

**Issue by dpshelio** [sunpy/sunpy#2895]
VSO's website can work with this type of queries ([firs option](https://sdac.virtualsolar.org/cgi/search)). However, the query below takes quite long time... 
```python
>>> from sunpy.net import vso               
>>> client = vso.VSOClient()
>>> qr = client.search(vso.attrs.Time('2013-05-18 23:59:00', '2013-05-19'))
>>> print(len(qr))
0
```

![100 seconds and searching](https://user-images.githubusercontent.com/963242/51087985-49894200-1752-11e9-9d28-fd8acc968a27.png)

I believe what's going on with SunPy is that it times out without getting any of the answers and returns 0. I believe a more informative message about what's going on will help the user to modify the query so it doesn't believe there were not observations recorded by any telescope (for example to choose an instrument/provider/wavelength...)

and after 500 seconds:
![0 results](https://user-images.githubusercontent.com/963242/51088055-3d51b480-1753-11e9-86f4-ae0999ac0f36.png)

0! (no, not 0!=1, but *nada*) even in the previous page I was shown the numbers of matches for each provider.

This is related with #568 - where the same query was used - and #1589.

**Comment by dpshelio** [comment]
@AlisdairDavey - I think this is also a problem on VSO's side.

**Comment by nabobalis** [comment]
Do we want to support this kind of search? I am not sure we want to allow this kind of search.

**Comment by Cadair** [comment]
I think we want the VSOClient to support it, as it's a valid VSO query. I think, *in theory* I would also like Fido to be able to support this, but it would require a slightly larger refactoring in Fido.

**Comment by nabobalis** [comment]
I am sure, it is a valid search. But it kind of feels like we are DDOSing the VSO with that kind of search.

**Comment by sudozer** [comment]
> I believe what's going on with SunPy is that it times out without getting any of the answers and returns 0.

yes

> VSO should have it's own protections in for size of query

At SDAC we have NASA-mandated limits to the filesize of the actual xml message sent to the machines (modsecurity).  We have had issues in the past with users sending very large getdata requests and having the xml message be large enough to trigger that failure & return a code 413.

We do not have a hard "you cannot send a query this broad" backstop anywhere in the code.  Certain providers do have different query modes that trigger past a certain threshold (e.g. querying the GONG network for more than I think a week at once will trigger code within the data provider that now only returns tarballs for entire days instead of links to individual images)

The VSO is designed to be fairly-liberal in terms of which particular parameters you can use to request data.  The only absolutely-required parameter is of course a date range, but searching on just a date range (even a small one) will hang, possibly due to issues with some of the more obscure, rarely-used data providers or the servers where the data is hosted.  

I've known about this for a while, I've never considered it a real concern.  I can't speak to the validity of a query to all data providers at once, not being a scientist myself.  Though if it's being discussed here maybe we should talk about it within the VSO too.  If push comes to shove I can possibly change the error message on the website to express that a timeout has occurred instead of using the no records returned message which is misleading.

**Comment by jhourcle** [comment]
The problem is that the VSO needs to get results from all data providers so that it can merge them together to return a response to the client.

If any of the data providers are slow to respond, it can result in the VSO not being able to respond before the client times out.  When someone sends a query that *only* has a time range, a lot of providers are contacted (as there's no reason to exclude them unless they don't have any data from that time range), making this more likely to happen.

It's possible that there might be some database tuning that can be done at the individual data providers if someone can figure out which ones are being slow ... and I wouldn't be surprised if the SDAC is part of the problem these days.  (the database server is actually *less* powerful than it used to be, in terms of CPU and RAM (not sure about disk speed) ... but there was a push to increase the record limits recently that were implemented specifically to keep this from happening ... and I don't know if that was done or not

**Comment by abhijeetmanhas** [comment]
@nabobalis no error now, both for Fido and VSO. Probably close or label with `close?` .

```dart
from sunpy.net import vso, attrs as a, Fido
import astropy.units as u
client = vso.VSOClient()
qr = Fido.search(a.Time('2013-05-18 23:59:00', '2013-05-19'))
qr
Start Time [1] | End Time [1] | Source | Instrument | Type | Wavelength
-- | -- | -- | -- | -- | --

1995-12-02 00:00:00 | 2020-01-01 00:00:00 | SOHO | VIRGO | FULLDISK | None
1995-12-02 00:00:00 | 2020-01-01 00:00:00 | SOHO | VIRGO | FULLDISK | None
1995-12-02 00:00:00 | 2020-01-01 00:00:00 | SOHO | CELIAS | ['N/A'] | None
1995-12-02 00:00:00 | 2020-01-01 00:00:00 | SOHO | CELIAS | ['N/A'] | None
1995-12-02 00:00:00 | 2020-01-01 00:00:00 | SOHO | CELIAS | ['N/A'] | None
1995-12-07 00:00:00 | 2020-01-01 00:00:00 | SOHO | COSTEP | ['N/A'] | None
1995-12-07 00:00:00 | 2020-01-01 00:00:00 | SOHO | COSTEP | ['N/A'] | None
1995-12-07 00:00:00 | 2020-01-01 00:00:00 | SOHO | COSTEP | ['N/A'] | None
1995-12-07 00:00:00 | 2020-01-01 00:00:00 | SOHO | COSTEP | ['N/A'] | None
1995-12-07 00:00:00 | 2020-01-01 00:00:00 | SOHO | COSTEP | ['N/A'] | None
... | ... | ... | ... | ... | ...
2013-05-19 00:00:00 | 2013-05-19 23:59:59 | SOHO | CELIAS | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | ERNE | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | ERNE | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | ERNE | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | ERNE | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | ERNE | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | COSTEP | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | COSTEP | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | COSTEP | ['N/A'] | None
2013-05-19 00:00:00 | 2013-05-20 00:00:00 | SOHO | COSTEP | ['N/A'] | None
```
