### ISSUE TITLE
Download Sample Data into a hidden directory

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#2959]
Currently `import sunpy.data.sample` will download our [sample data](http://data.sunpy.org) to `~/sunpy` as specified by [working dir](https://github.com/sunpy/sunpy/blob/master/sunpy/data/sunpyrc#L24) in the config file.

I propose that we move to using [appdirs](https://github.com/ActiveState/appdirs) to determine the "user data directory" which is platform dependant and used for applications to put data they need (not to be directly accessed by the user). This move would mean that we wouldn't create `~/sunpy` until the user used `Fido` with the default `path=` argument.

My reasoning for this is that we only expose the sample data to users through the `import sunpy.data.sample` interface, so it is irrelevant to the users where those files actually reside on disk, and that if this is the case then we shouldn't be creating a directory in their home directory to do it.

**Comment by Cadair** [comment]
ping @DanRyanIrish @ehsteve @nabobalis @astrofrog :grin:

**Comment by nabobalis** [comment]
So I am in favour for two reasons:

1. We don't expect users to interact with the sample-data through any file manager or creating some custom path. But through importing the data module. Therefore we can move it or hide it however we want.
2. We should be following standards for each OS when it comes to directory usage/placement of files. 
3. Creating a sample-data client to use with Fido to me seems only a good idea if we use it as an example on how to create downloader clients for developers/anyone interested. Otherwise, I think it is a bad idea to try and expose users to using Fido to download our sample-data manually. 

The only downside I can see right now is that if a dev has to delete the sample-data, it is a bit more opaque. But we can document this in the developer documentation.

**Comment by astrofrog** [comment]
I'm in favor of this 👍  - I find it annoying to have a sunpy directory created in my home directory on a regular basis.

**Comment by nabobalis** [comment]
I mean that too. I have forever hated a folder and I delete it everytime I open my home dir. Unfortunately this means @Cadair AWS bill increases with time.

**Comment by Cadair** [comment]
So you mean hiding it away will save me money on my AWS bill?! SOLD!

**Comment by nabobalis** [comment]
The main reason I also have to delete it, any tests that I run that download data, don't clean up after themselves. So I get a million files in it too. But that's off topic
