### ISSUE TITLE
Improve documentation of overplotting in world coordinates for Map plots

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3018]
Consider the following example, plotting a map, and then adding a scatter point at (0, 0). I would expect the point to be in the middle of the plot, but it is at the bottom LH corner instead, which I guess is actually the origin of the axes, but the axis labels have been somehow modified to hide this:

```python
import sunpy.map
from sunpy.data.sample import AIA_193_IMAGE
import matplotlib.pyplot as plt
import astropy.units as u

aiamap = sunpy.map.Map(AIA_193_IMAGE)
ax = plt.subplot(1, 1, 1, projection=aiamap)
aiamap.plot(axes=ax)
ax.scatter(0 * u.deg, 0 * u.deg)

plt.show()
```
![aia](https://user-images.githubusercontent.com/6197628/55003306-1247d480-4fd0-11e9-9c3d-028aa5ed8854.png)

As far as I can tell this is wrong, and the axes origin should be at the center of the image.

**Comment by Cadair** [comment]
To plot in world coordinates you need to specify the frame you wish to overplot in using the `transform=` kwarg as described in the wcsaxes docs: http://docs.astropy.org/en/stable/visualization/wcsaxes/overlays.html#world-coordinates

So for this example it would be:

```python
import sunpy.map
from sunpy.data.sample import AIA_193_IMAGE
import matplotlib.pyplot as plt
import astropy.units as u

aiamap = sunpy.map.Map(AIA_193_IMAGE)
ax = plt.subplot(1, 1, 1, projection=aiamap)
aiamap.plot(axes=ax)
ax.scatter(0 * u.deg, 0 * u.deg, transform=ax.get_transform("world"))

plt.show()
111

**Comment by dstansby** [comment]
That is really odd and unintuitive, but I guess is an upstream WCSAxes issue? Naïvely I can't see why the WCS coordinates can't be the same as the Axes coordinates.

**Comment by Cadair** [comment]
I wonder if @astrofrog could provide a bit of bonus context here?

**Comment by astrofrog** [comment]
@dstansby - for cases like this where the lon/lat nicely line up with pixel coordinates, I might look like it would be more intuitive to just give the angles to ``scatter``, however for many astronomical images, the 'world' coordinates don't line up with pixel coordinates, and furthermore the grid lines are curved, not straight. However, you are then still showing the image in pixel coordinates (not stretching it so that e.g. RA/Dec grid lines are always lined up with the axes and linear axes), hence why we've adopted the picture that in WCSAxes by default everything is done in pixel coordinates (because imshow is in pixel coordinates), and you have to be explicit if you mean world coordinates.

Note that there is a ``plot_coord`` method that can be used to plot directly in world coordinates without having to specify a transform:

https://github.com/astropy/astropy/blob/master/astropy/visualization/wcsaxes/core.py#L262

**Comment by dstansby** [comment]
Thanks for the explanation! Is plotting in pixel coordinates also done with angular units (ie. degrees)? If not, it might make sense to either error or warn if the user tries to plot data with units without the world transform.

**Comment by astrofrog** [comment]
@dstansby - good point, we could consider catching the case where units are passed and either give an error or even do the smart thing. Units aren't used for pixel space plotting.

**Comment by Kate028** [comment]
Hey @nabobalis this issue is still open! What are we supposed to do here?

**Comment by nabobalis** [comment]
> Hey @nabobalis this issue is still open! What are we supposed to do here?

I'm not sure.

**Comment by dstansby** [comment]
I think this is really an upstream astropy issue (trying to plot on a `WCSAxes` in degrees should raise an error), and on the sunpy end is made a lot better with #4867, so I'm going to close.
