### ISSUE TITLE
Map utilities examples are needed

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#3072]
### Description

Once #2972 has been accepted there should be some gallery examples describing the use of the map utilities.

**Comment by samriddhi-dev** [comment]
Am I supposed to write examples for differential rotation and solar rotation?

**Comment by nabobalis** [comment]
No I think we have a range of examples for those two items. What the focus would be on the functions in maputils.py (https://github.com/sunpy/sunpy/blob/master/sunpy/map/maputils.py)

**Comment by Cadair** [comment]
see also #5095

**Comment by m11dedhia** [comment]
@samriddhi-dev are you working on it? or should I start adding examples too?

**Comment by samriddhi-dev** [comment]
Hi,
I am working on it

**Comment by wtbarnes** [comment]
Given that the scope of this issue seems to be related to differential rotation and that we already have several examples related to differential rotation (https://docs.sunpy.org/en/stable/generated/gallery/plotting/simple_differential_rotation.html#sphx-glr-generated-gallery-plotting-simple-differential-rotation-py and https://docs.sunpy.org/en/stable/generated/gallery/differential_rotation/reprojected_map.html#sphx-glr-generated-gallery-differential-rotation-reprojected-map-py), I'm going to close this.
