### ISSUE TITLE
vso.VSOClient() doesn't return data anymore!

### ISSUE THREAD

**Issue by MjdMahasneh** [sunpy/sunpy#3097]
I have been using the VSO module to download some SOHO EIT and MDI data recently, it was working flawlessly until last night! it stopped returning any data even for dates that I have downloaded using using the same code before. Is there an explanation for this?

**Comment by nabobalis** [comment]
The most likely one would be something is broken in the VSO side. More accurately, the service that provides SOHO data to the VSO is having issues. We can see if we can get in touch with some VSO people to enquire.

**Comment by MjdMahasneh** [comment]
@nabobalis Thank you for your quick response, as usual 👍  

I think that might be the reason, is this a common issue? If so, do you think it will be back soon?

**Comment by nabobalis** [comment]
We have noticed issues with it in our online testing every so often. The only thing we can do is ask and wait. Normally service is restored at most,  after a few days.

**Comment by AlisdairDavey** [comment]
Could you give me (the VSO folks) some more information, specifically which instruments (both EIT/MDI?) you are trying to download data for and for which dates / times. I suspect this is an issue with accessing the disks on which the data resides again, in which it should be able to be fixed fairly quickly.

**Comment by jhourcle** [comment]
Could you give us the specific code that you're using to search the VSO, and any information or results that get displayed?

Getting data using the VSO is actually a three step process, so knowing *where* in the process the failure is greatly helps to track down problems.  (there's the 'Query' phase, where you send search parameters and get back lists of records that match, then there's 'GetData' where you send a list of identifiers you're interested in and for most cases get back a list of URLs to download, and then there's actually trying to retrieve those URLs)

**Comment by MjdMahasneh** [comment]
@nabobalis Thank you for your response, I will wait and see hopefully it won't take much time. 

Best regards.

**Comment by nabobalis** [comment]
@MjdMahasneh I would strongly suggest you  reply to @jhourcle and @AlisdairDavey messages.

**Comment by MjdMahasneh** [comment]
@nabobalis I apologies, I haven't refreshed my we browser and I didnt see the recent comments from @AlisdairDavey and @jhourcle 

I am requesting EIT (284, 195, 171, and 304) along with MDI. I am trying for different periods from the years 2002, 03, 04, 05, 08, and 2010. 

I use basic queries such as :

`start_day = datetime(2010, 12, 14)
end_day = datetime(2010, 12, 30, 23)
qr = client.query_legacy(tstart =  start_day, tend = end_day, instrument = 'EIT', min_wave = '284', max_wave= '284', unit_wave = 'Angstrom', resolution = 1.0)
res = client.fetch(qr, path='./response/{instrument}/interval /' +'{file}.fits').wait()'

And I receive an empty response for any of the queries. 

To elaborate further, the same requests went through flawlessly last night, but today's morning I had no luck with any of my requests.

**Comment by MjdMahasneh** [comment]
@nabobalis @AlisdairDavey @jhourcle Good news, I have just tried to run the script again and it worked with no problem. I am not sure what have caused it to return empty response earlier. 

Many thanks.

**Comment by sudozer** [comment]
Hi everybody, 
I received an alert this morning that apache was down on the server which routes VSO queries to their respective databases.  Our System administrator spoke with me yesterday about that particular server being out of compliance with the security policies at NASA and he did some work on it last night.  I imagine he might have forgotten to restart apache when he wrapped up his work, or something he did twisted up the running instance of apache, either way I brought it back up first thing this morning and I've been keeping an eye on it.

This problem would have broken any queries to SoHO, as well as STEREO, EUNIS, and Hinode.  Queries to EUNIS are still down due to an expired HTTPS cert, and we may end up moving that dataset to another server.  I didn't expect this work to bring down that server and I will certainly say so if anything we do is expected to interrupt the data pipeline in the future.

Jacob

**Comment by Cadair** [comment]
Thanks everyone :smile:
