### ISSUE TITLE
Update gallery to use map utils for coordinate arrays

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy#3177]
The new map utils provide convenience functions to get arrays of all pixels coordinates but they are not currently used in the gallery examples.

**Comment by Swapnil99007** [comment]
I would like to work on this issue, can you please elaborate it a little bit ?

**Comment by nabobalis** [comment]
In https://github.com/sunpy/sunpy/blob/master/sunpy/map/maputils.py we added a series of helper functions to do common tricks that users might want to do. In the gallery examples (the example folder at the root of the sunpy repository) some of those files need to be updated.

But since there is no list of examples you will have to go through each one and see if any of those functions can replace snippets of code in those files. If you can't find any, we can close this issue instead.

**Comment by Swapnil99007** [comment]
Basically, I have to go through each example in the example gallery and check whether those utility functions can be used in those examples, if so we need to replace the old code with the modified version with utility functions being called.

**Comment by Swapnil99007** [comment]
> In https://github.com/sunpy/sunpy/blob/master/sunpy/map/maputils.py we added a series of helper functions to do common tricks that users might want to do. In the gallery examples (the example folder at the root of the sunpy repository) some of those files need to be updated.
> 
> But since there is no list of examples you will have to go through each one and see if any of those functions can replace snippets of code in those files. If you can't find any, we can close this issue instead.

I have gone through each and every code in the Example Gallery and the utility functions have already been used in a few examples. Other than those examples, I haven't found any code in which we can use the utility functions to our benefit.

**Comment by nabobalis** [comment]
In that case, I will close this issue. Thanks @Swapnil99007
