### ISSUE TITLE
Create a Test or a function to report status on all remote servers SunPy pings during a test run

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#3303]
Currently, when a remote server goes down, we do not know if it is something we might have broken our side or if it is a remote issue.

To work towards fixing this, some function (we can turn into a test) that we can run  that will report back the status of all remote servers we ping during our test suite and doc build.

We would need to somehow capture the range of IPs or URLs we request during a `pytest --remote-data=any` run and use that as a foundation for this.

**Comment by devanshshukla99** [comment]
Hi,
During `pytest --remote-data=any` Sunpy made requests to the following urls,
```
https://ssd.jpl.nasa.gov/
https://naif.jpl.nasa.gov/
https://datacenter.iers.org/
http://ipv4.download.thinkbroadband.com/
http://data.sunpy.org/
http://docs.virtualsolar.org
http://netdrms01.nispdc.nso.edu
http://vso.nso.edu/
http://proba2.oma.be/
```
If I understand correctly, we want to make a function/test to ping to each url to check if its online right?

I used a third-party software to intercept the requests since I'm not aware of any pure-python implementation.
So, I guess we'll have to manually update this list for any new tests, feel free to correct me.

**Comment by nabobalis** [comment]
We don't want to have to manually update the list if we add more urls.
It will have to be in python.

**Comment by devanshshukla99** [comment]
👍
I'll try,
Thanks

**Comment by devanshshukla99** [comment]
Hey @nabobalis, so, I made a pytest plugin to intercept outgoing connection requests and dump it to a file; it works though a command line arg, 
`--intercept=[dump file]`

To promote more general use, thoughts about creating a new package under sunpy, like `pytest-remotedata` in astropy?

**Comment by nabobalis** [comment]
Errr, good question. Not sure if I am pro another package under the sunpy org, (@Cadair can chime in as he is the one with the power to do so). 

You could create your own package instead. Otherwise, we could add it to sunpy for now?

**Comment by Cadair** [comment]
What does this do with the urls once it intercepts them? I think the best thing to do is add it to sunpy for now and we can spin it out later if we want.

**Comment by devanshshukla99** [comment]
So, the plugin works by monkey patching urllib, requests and socket; each time a function tries to connect to internet it stores the url and throws a Runtime Error, then dumps the urls to file so that they can be pinged during normal pytest run.

Regarding the plugin in sunpy, what would be the best location, how about a plugins folder in the rootdir?

**Comment by nabobalis** [comment]
Can it live under the tests subfolder?

**Comment by devanshshukla99** [comment]
Yes, 👍
