### ISSUE TITLE
Round-tripping issue with sunpy.coordinates

### ISSUE THREAD

**Issue by astrofrog** [sunpy/sunpy#3328]
### Description

I've run into an issue when trying to transform between two helioprojective frames. Here's a MWE to reproduce this:

```python
import sunpy.map
from astropy import units as u
from astropy.wcs.utils import wcs_to_celestial_frame
from astropy.coordinates import UnitSphericalRepresentation

map1 = sunpy.map.Map('aia_lev1_304a_2011_01_01t00_00_08_12z_image_lev1.fits')
map2 = sunpy.map.Map('secchi_l0_a_img_euvi_20110101_20110101_000615_n4eua.fts')

frame_in = wcs_to_celestial_frame(map1.wcs)
frame_out = wcs_to_celestial_frame(map2.wcs)

data = UnitSphericalRepresentation(0.1 * u.deg, 0.2 * u.deg)

coords = frame_in.realize_frame(data).transform_to(frame_out)

rep = coords.represent_as('unitspherical')

coords = frame_out.realize_frame(rep).transform_to(frame_in)

rep = coords.represent_as('unitspherical')

print(rep)
```

**Note:** The data can be downloaded [here](https://www.dropbox.com/sh/i9ibhulne67rm1z/AAC4qD11xt5CoY9yu4EPgplqa?dl=0)

Note that the slightly convoluted way of getting the representation and attaching it back to a frame is because I need to do something along these lines in the reproject package.

### Expected behavior

```
<UnitSphericalRepresentation (lon, lat) in deg
    (0.1, 0.2)>
```

### Actual behavior

```
<UnitSphericalRepresentation (lon, lat) in deg
    (0.0996353, 0.20004398)>
```

### Steps to Reproduce

Run the script above!

### System Details

  - SunPy Version: 1.0.2
  - Astropy Version: 3.2.1
  - Python Version: 3.7.4
  - OS information: MacOS X 10.14.6

**Comment by ayshih** [comment]
Can you do me a favor and try running your example on the just-released 1.0.3?  I fixed some bugs with HPC->HPC transformations, so maybe your issue is already fixed.

**Comment by astrofrog** [comment]
@ayshih - the output is in radians with 1.0.3 but once I convert to degrees I get the same as above.

**Comment by ayshih** [comment]
Rats!  Okay, I'll track this down.

**Comment by astrofrog** [comment]
Interestingly this works:

```python
coords = frame_in.realize_frame(data).transform_to(frame_out).transform_to(frame_in)

rep = coords.represent_as('unitspherical')

print(rep.lon.deg, rep.lat.deg)
```

so there's something about getting the representation from the frame and adding it back to the frame that's not working properly.

**Comment by Cadair** [comment]
oh so maybe this *is* an astropy problem :stuck_out_tongue:

**Comment by ayshih** [comment]
No, I suspect the problem is the extra step that you do in the OP of converting to `UnitSphericalRepresentation` before transforming back.  We have to do another conversion from 2D to 3D that isn't done in your second example.

**Comment by ayshih** [comment]
Yup, the problem is that extra step, for two reasons:

- The two files you are using have a slightly different values for the radius of the Sun (696 Mm versus 695.7 Mm).  That means when you convert to 2D and then back to 3D, the coordinate is shifted along the line of sight.
- The angle between the two observers relative to Sun center is ~86 degrees, which means that a line-of-view shift from one perspective manifests nearly entirely as a transverse shift from the other perspective.

If you set `frame_out` to have the same value of the `rsun` attribute as `frame_in` (using `replicate_without_data()`), the round trip will be a lot closer.

So, I think everything is working as designed, even if the result is non-intuitive.

**Comment by ayshih** [comment]
(P.S. Your Dropbox line to the data files actually doesn't have the original SECCHI file, so I grabbed it off of VSO instead.)

**Comment by astrofrog** [comment]
@ayshih - ok thanks, that makes sense! Removing the representation step does fix things so that's probably the easiest fix. However, I now also see a similar issue if I just use the APE 14 API with Sunpy WCS objects:

```
>>> import sunpy.map
>>> map1 = sunpy.map.Map('aia_lev1_304a_2011_01_01t00_00_08_12z_image_lev1.fits')
>>> map2 = sunpy.map.Map('secchi_l0_a_img_euvi_20110101_20110101_000615_n4eua.fts')
>>> pixel1 = 2048, 2048
>>> pixel2 = map2.wcs.world_to_pixel(map1.wcs.pixel_to_world(*pixel1))
>>> map1.wcs.world_to_pixel(map2.wcs.pixel_to_world(*pixel2))
[array(2037.46136725), array(2049.20944788)]
```

Any ideas on what could be causing this?

**Comment by ayshih** [comment]
An important correction to what I said earlier: the SECCHI header does not include the radius of the Sun, so the Map object uses the value in SunPy's constants (the IAU 2015 value of 695.7 Mm).  So, in a sense, this mismatch is self-inflicted by SunPy, and one could imagine that if we knew that a default value was being used for one side (here, SECCHI), we'd be comfortable with replacing it with an explicit value from the other side (here, AIA).  However, with all of the layers and the projection, I don't know how you'd transport that information.

The bug with the APE14 API is essentially the same bug as the OP because casting it as a pixel is analogous to representing as `UnitSphericalRepresentation`.

**Comment by ayshih** [comment]
@astrofrog Since there doesn't appear to be an actual bug on the `sunpy.coordinates` side, can I close this issue?

**Comment by astrofrog** [comment]
Yes that's fine - I'll just document things in reproject to avoid this issue.
