### ISSUE TITLE
Observer property not considered in Map submap method

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#3340]
### Description

The observer properties of the bottom_left and top_right coordinates passed in to the Map submap method are not considered when defining the area of the submap.

### Expected behavior

The role of the observer property in the submap method should be defined and implemented. 

### System Details

  - SunPy Version: master, 1.0+, 0.9+

**Comment by Cadair** [comment]
The only real issue I see here is if the transform returns NaNs. What I would thing would be a good solution is to transform both the input coordinates to the map coordinate frame and if any of the results are NaN raise an error helpfully saying that the transform isn't valid.

**Comment by wafels** [comment]
What about allowing input that defines the top left and bottom right coordinates just using arcseconds? This is similar to the pixel input. This avoids the need for non-asked-for coordinate transformation.

**Comment by Cadair** [comment]
What happens when your map is in HGS (Plate Caree) or in HCRS or some other non-solar frame? We have to have these inputs be `SkyCoord` to be able to correctly interpret the intent of the user.

We also can't emit logs / warnings in the coordinate stack for off disk transforms, as WCSAxes and similar things often do out of bounds coordinate transforms to determine the edges of grids etc.

I think this therefore has to raise a warning in Map, the challenge is developing some code to reliably detect and inform the user about different potential issues with the SkyCoords they provide.

**Comment by wafels** [comment]
How about raising an error when the frame of the input coordinates are not the same as the map frame?

**Comment by Cadair** [comment]
I am not sure even that is trivial. I would rather throw an error on NaN, as sometimes you might want to pass in a different coordinate? Like if you want to cut out a box defined in HGS in both a stereo and an AIA image for instance.

**Comment by wafels** [comment]
Also, bottom_left and top_right don't make any sense as names for these coordinates since we don't verify that the bottom left coordinate passed in is actually "below" and to the "left" of the top right coordinate.  Similarly for the top right coordinate.

**Comment by dstansby** [comment]
I think `draw_rectangle` and `submap` now transform `top_right` into the frame of `bottom_left`, so is this fixed? A short, self contained example would be useful, as I'm not 100% sure what the issue here is.

**Comment by Cadair** [comment]
I am pretty sure this has always worked. The `pixel_to_world` method took this into account as part of the transform. Either way, unless someone can provide an example of this not working I am going to close it.
