### ISSUE TITLE
The code owners change dosen't seem to be working

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3347]
It didn't trigger on #3346

**Comment by Cadair** [comment]
I did that manually.

**Comment by ayshih** [comment]
Ha!  Never mind!

**Comment by ConorMacBride** [comment]
I think this is working again. (Or maybe review requests are still being manually triggered?) I double checked the `CODEOWNERS` configuration and corresponding teams and it all seems fine.

**Comment by nabobalis** [comment]
If I recall, it still does not request the actual github user?

**Comment by nabobalis** [comment]
@ConorMacBride, I don't get email alerts on emjoi use. So if something is unclear, you should leave a comment.

So the original idea (@Cadair will correct me if I was mistaken) was that we assign people to the codeowners file and then instead of that "package" gets assigned for review, the person(s) who are in that group gets assigned for review instead. 

I am unsure if people who are part of the codeowners get an alert for a PR review.

**Comment by ConorMacBride** [comment]
@nabobalis, yes that makes sense. (The emoji was just a general disappointment it still isn't working.) The teams all have write access to the repository so that shouldn't be the problem. 

Are any of these setting incorrect? https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team

**Comment by nabobalis** [comment]
Only @Cadair can check.

**Comment by Cadair** [comment]
It requests the team and the team should get a notification?

**Comment by nabobalis** [comment]
Then we close this and move on?
