### ISSUE TITLE
HeliographicCarrington doesn't error if obstime isn't supplied

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3374]
[The docs](https://docs.sunpy.org/en/latest/api/sunpy.coordinates.frames.HeliographicCarrington.html) state that:

>... (note that obstime must be supplied as a keyword):

But the following code runs without error:
```python
import astropy.units as u
from sunpy.coordinates import frames

lon = [1, 2] * u.deg
lat = [1, 2] * u.deg
r = [1, 2] * u.au

c = frames.HeliographicCarrington(lon=lon, lat=lat, radius=r)
```

I think that this should error given that `obstime` hasn't been provided to `HeliographicCarrington`.

**Comment by ayshih** [comment]
To be clear, the documentation is saying that if you want to specify `obstime`, you need to supply it as a keyword argument as opposed to a positional argument.  (The context is the example instantiations that follow that sentence.)  It's *not* saying that `obstime` must be supplied in all situations.

There are (narrow) use cases to use a frame like `HeliographicCarrington` without a fully defined observer, which is why `obstime` can be left unspecified.  Of course, trying to transform to any other frame without specifying an `obstime` will not work.

**Comment by dstansby** [comment]
Ah I didn't realise, I've submitted a PR to clarify the wording that confused me.
