### ISSUE TITLE
Transposed HMI image in the examples

### ISSUE THREAD

**Issue by PaulJWright** [sunpy/sunpy#3516]
In the examples, such as [this](https://docs.sunpy.org/en/stable/generated/gallery/plotting/aia_example.html#sphx-glr-generated-gallery-plotting-aia-example-py), SDO/AIA image is plotted in the usual manner: that is to say [1000",1000"] is located in the top-right, and [-1000",-1000"] located in the bottom-left. 

In the HMI example [here](https://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/downloading_hmi.html), the image has co-ordinates that are the transpose of the AIA image.

While setting the projection is necessary to ensure that pixels can be converted accurately to coordinates values, altering the notebook to include: ```ax = plt.subplot(projection=hmi_map)``` does not correct this.

Compare: 

```
from sunpy.data.sample import AIA_171_IMAGE
aiamap = sunpy.map.Map(AIA_171_IMAGE)
fig = plt.figure()
ax = plt.subplot(projection=aiamap)
aiamap.plot()
```

```
hmi_map = sunpy.map.Map(downloaded_file[0])
fig = plt.figure()
ax = plt.subplot(projection=hmi_map)
hmi_map.plot()
```

----
The plots from the respective notebooks:

<img src="https://user-images.githubusercontent.com/8172222/69117312-1daaad00-0a44-11ea-8bba-79fb4c24c13e.png " alt="AIA" width="300"/><img src="https://user-images.githubusercontent.com/8172222/69117282-0d92cd80-0a44-11ea-8037-66ebf13c8e4f.png" alt="HMI" width="300"/>

**Comment by wtbarnes** [comment]
The HMI data are rotated 180 degrees relative to AIA. The HPC coordinates are oriented correctly relative to the image because `Map` knows about this orientation from 'CROTA2' key in the FITS header (i.e. `hmi_map.meta['CROTA2']` should be close to 180). This is also reflected in the `hmi_map.rotation_matrix` attribute.

To remove the roll angle, you can use the `.rotate` method on `Map`, .e.g.

```python
m_rot = hmi_map.rotate()
```

Note that you don't have to specify the angle to rotate through as `Map` is aware of the roll angle (from the header) and will diagonalize the rotation matrix by default (i.e. it will align solar north with the y-axis of your image).

We probably should do a better job at making this clear, at least in the examples, because this question tends to pop up quite frequently, e.g. [this nearly identical issue that I created a while back!](https://github.com/sunpy/sunpy/issues/1847).

**Comment by PaulJWright** [comment]
Ah, apologies for the duplicate issue. 

I think that just adding that line into the HMI notebook would suffice?

**Comment by PaulJWright** [comment]
... although that'd also have to account for ```WARNING: SunpyUserWarning: Setting NaNs to 0 for higher-order scikit-image rotation. [sunpy.image.transform]```

**Comment by wtbarnes** [comment]
This is because there are `NaN`s in the HMI data which scikit-image, for an interpolation order of 4 (the default), will set to zero. You can avoid this by using a 3rd order interpolation, i.e.

```python
hmi_map.rotate(order=3)
```

**Comment by wtbarnes** [comment]
Was going to create an issue for the clarification in the example, but looks like #3233 pretty much already covers this. If you wanted to add an example to address this, I'd be happy to help.

**Comment by PaulJWright** [comment]
Would be happy to contribute!

**Comment by wtbarnes** [comment]
Great! A good place to start might be having a look at [example gallery section of the dev guide](https://docs.sunpy.org/en/latest/dev_guide/example_gallery.html). We could either add a new example that addresses this or just modify the existing HMI example that you linked to above.

**Comment by wtbarnes** [comment]
If it's OK with you, I propose that we close this issue and move this discussion over to #3233.
