### ISSUE TITLE
`image.transform.affine_transform()` can produce values outside of the range of the input array (e.g., more negative)

### ISSUE THREAD

**Issue by Raahul-Singh** [sunpy/sunpy#3718]
When a map is rotated using `map.rotate` It leads to a general yellow-washing of the new map.
map without rotation and scaling :
![map](https://user-images.githubusercontent.com/40922068/72879657-5a847000-3d23-11ea-9db8-1091bfe80b5b.png)
map without rotation and scaling = 1.5 :
![Scale1 5](https://user-images.githubusercontent.com/40922068/72879664-5d7f6080-3d23-11ea-9a6c-b2c123534b85.png)

map with rotation = 45 degree and scaling = 4 :
![rot45_sc4](https://user-images.githubusercontent.com/40922068/72879739-84d62d80-3d23-11ea-9651-eb748b65b4eb.png)

map with rotation 45 degree and  scaling = 2 :
![Figure_1](https://user-images.githubusercontent.com/40922068/72879844-bb13ad00-3d23-11ea-8926-dc5595eb652f.png)

map without rotation degree and scaling = 2 :
![Figure_2](https://user-images.githubusercontent.com/40922068/72879872-ccf55000-3d23-11ea-83b7-5cd9daac50be.png)

map with rotation 45 degree and no scaling :
![45sc0](https://user-images.githubusercontent.com/40922068/72880155-54db5a00-3d24-11ea-9710-303e8436fad5.png)

I observed that the yellowness vanishes around scale = 1.812 without rotation, and on different thresholds for different rotations.

**Comment by Cadair** [comment]
The effects on the plotting are because of where the 0 point is on the colour map. Setting `plot(vmin=0)` will fix the display.

The more interesting question here is how and why are negative values appearing in the map during the call to `rotate()`.

**Comment by ayshih** [comment]
I've looked into this a little, and it appears to be due to using SciPy's `affine_transform()` (i.e., the fallback).  Everything looks fine with scikit-image's `warp()` (i.e., the default), so I'm guessing that @Raahul-Singh doesn't have scikit-image installed.

It doesn't look like we have many tests that test the SciPy fallback.

**Comment by ayshih** [comment]
Ah, I've gotten to the bottom of this.  Arguably SciPy has the correct behavior here because higher-order interpolation can produce excursions (in this case, negative values).  Here's a slice through the problematic spot in the `scale=1.5` example at different orders of interpolation in SciPy:

![fig2](https://user-images.githubusercontent.com/991759/72954667-2b8fed80-3d67-11ea-886a-8d6322632bcd.png)

If we use scikit-image instead, we don't see the same negative values at high orders of interpolation:

![fig1](https://user-images.githubusercontent.com/991759/72954660-27fc6680-3d67-11ea-9443-97b8bc1c40a1.png)

But, that's not because scikit-image knows something that SciPy doesn't; it's because scikit-image's `warp()` – [by default](https://scikit-image.org/docs/dev/api/skimage.transform.html#warp) – clips the output range to the input range.  We should debate whether we should set `clip=False` for `warp()`, and then the behavior here would be expected on all setups and should instead be documented.

**Comment by Raahul-Singh** [comment]
@ayshih Could you please share the script you used to figure this out? I was trying to do so as well and resorted to plotting after every other step in `rotate` :sweat_smile:. Also, please share the script for generating those plots as well!!

**Comment by wtbarnes** [comment]
This is really interesting. We did some testing with aiaprep a while back looking at the two different interpolation methods for a range of orders and found more “ringing” in the scipy method than the scikit image method. I guess this was because of the clipping that you mention here.

**Comment by Cadair** [comment]
wait?! scipy has support for orders > 3 now?!

Why are we even using scikit-image?

**Comment by ayshih** [comment]
> @ayshih Could you please share the script you used to figure this out?

You'll need to have scikit-image installed, otherwise this code will just use SciPy everywhere.

```python
>>> Map(AIA_171_IMAGE).rotate(scale=1.5).plot()  # defaults to use_scipy=False and order=3
>>> plt.colorbar()
>>> plt.show()
```
![fig3](https://user-images.githubusercontent.com/991759/72991612-4b073480-3dc0-11ea-9c36-0e2be732c509.png)

```python
>>> Map(AIA_171_IMAGE).rotate(scale=1.5, use_scipy=True).plot()  # defaults to order=3
>>> plt.colorbar()
>>> plt.show()
```
![fig4](https://user-images.githubusercontent.com/991759/72991616-4cd0f800-3dc0-11ea-8f12-04f0c8227e3a.png)

And for the two line plots:
```python
>>> for order in range(6):
...     plt.plot(Map(AIA_171_IMAGE).rotate(scale=1.5, order=order).data[292, 940:950], label=f"order={order}")
>>> plt.title("Using scikit-image (the default)")
>>> plt.legend()
>>> plt.show()
```

```python
>>> for order in range(6):
...     plt.plot(Map(AIA_171_IMAGE).rotate(scale=1.5, use_scipy=True, order=order).data[292, 940:950], >>> label=f"order={order}")
>>> plt.title("Using SciPy (the fallback)")
>>> plt.legend()
>>> plt.show()
```

**Comment by ayshih** [comment]
> We did some testing with aiaprep a while back looking at the two different interpolation methods for a range of orders when rotating a disk of 1s surrounded by 0s (I.e. such that the edge of the disk was a discret step).

Amusingly, I only realized what was going on *because* the scikit-image output was suspiciously pinned to zero in those line plots.  It's not surprising that you missed it in your artificial test case, where zero was a desired value.

**Comment by ayshih** [comment]
> Why are we even using scikit-image?

Heh, is that the only reason we were using it?  Note that if we want clipping behavior (either optional or default), I don't think SciPy's `affine_transform()` has it as an option, so we'd have to implement it separately.

**Comment by Cadair** [comment]
I think that it was originally. It would certainly clean up the rotation code and our dependency tree if we could just rely on the scipy implementation.
