### ISSUE TITLE
Some VSO MDI queries are returning tar files with errors in

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3747]
See https://github.com/sunpy/sunpy/pull/3740#discussion_r373622339 for context, the following query:

```python
    results = client.search(
        va.Time('2011/1/1 01:00', '2011/1/1 01:02'),
        va.Instrument('mdi'))
    files = client.fetch(results[0:1])
```
returns a file named "mdi_vw_v_9466622_9466622.tar" which when expanded contains a file called `error_list.txt` with the following content:

> record = mdi.vw_V[2011.01.01_01:02:00_TAI], file = mdi.vw_V.2011.01.01_01:02:00_TAI.data.tas, message = cannot export Rice-compressed floating-point images

This seems to be a VSO issue, or maybe a JSOC one (where the data is coming from through VSO).

**Comment by pscherrer** [comment]
No problem with JSOC, tested at:
http://jsoc.stanford.edu/SUM14/D1256759376/S00000/

**Comment by abhijeetmanhas** [comment]
Tried the same query on VSO website, it showed no records found

**Comment by dstansby** [comment]
Could you update the original issue code with a self contained example?

**Comment by pscherrer** [comment]
The MDI.vw_V data is stored in cubes of 360 minutes, one minute each 
image.  The header data is as in all JSOC internal data stored in
the database and accessible via jsoc_info,  If you ask for individual
frames in exportdata you will get 360 files for each 6 hours, and since
this data is useful primarily for seismology using at least days and
often months at a time, a file per minute is a management issue.
The .tas == tiled array storage, are just FITS cubes but without
the per record metadata possible to add.  We are now working on
provideing such metadata as FITS binary tables as we will do for
data that has only metadata such as the observer location and HK data.
(housekeeping - temps, pointing offsets, etc.)
The vw_V is about 50 MB per 6 hours.

Also note that we are presently blocking netDRMS access to data in the 
lower number SUMS partitions until we get new drives in new servers that
arrived yesterday installed and the data migrated from 6-year old 
failing drives.  We have experience that shows with older drives
that have been used in JSOC with a lot of accesses, that once
one drive in a RAID partition fails, there is a good chance for
a second and even third drive to fail during a disk replacement
RAID rebuild.  So RAID is really only helpful for early-in-life
disk failures to be able to replace bad drives.  It may be that
VSO funneled requests are watching for the jsoc_fetch error
codes that will say no access for a while.

**Comment by Cadair** [comment]
Thanks for the info @pscherrer 

When this was reported I don't you had the disk issues (Feb), but might make it harder to reproduce now.

**Comment by pscherrer** [comment]
Occasionally visit the jsoc home page where the MOTD is at the top when 
there is something to report.
jsoc.stanford.edu

Now shows:
Due to concerns over the health of several SUMS disks, we are 
proactively blocking access to the data they contain until we can 
transfer the content to new media. The data impacted include many AIA, 
HMI, and MDI data series. In general this impacts mostly older data, but 
this also impacts some more recent data. This does not impact data 
generated after October 1, 2018 - all recently generated data will 
continue to be accessible. We expect to have all access completely 
restored by October 1, 2020, approximately.
