### ISSUE TITLE
Passing a norm from the plot_settings of one map to another modifies plot settings in place

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#3864]
### Description
When passing the normalization from the `plot_settings` dict of a map to the plot method of another map via the `norm` keyword, the new norm is ignored and the original normalization is modified in place such that the original map has the normalization of the new map.

### Expected behavior

The new map to plotted with the normalization of the original and the plot settings to not be modified in place.

### Actual behavior
The code snippet below produces the following (in this order):

![image](https://user-images.githubusercontent.com/8676141/76036326-be4cac00-5f11-11ea-9a35-5d62d10d0b46.png)
![image](https://user-images.githubusercontent.com/8676141/76036355-d91f2080-5f11-11ea-8954-d85cdbd4a9ea.png)
![image](https://user-images.githubusercontent.com/8676141/76036359-de7c6b00-5f11-11ea-9a05-905d35c3f87d.png)

### Steps to Reproduce

```python
import sunpy.data.test
import sunpy.map
import sunpy.data.sample
m = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
m_new = m._new_instance(np.where(m.data<100, -10000, m.data), m.meta)
m.peek(title='original')
m_new.peek(title='new', norm=m.plot_settings['norm'])
m.peek(title='original')
```

### System Details

  - SunPy Version: 1.1.1
  - Astropy Version: 4.0
  - Python Version: 3.8.1
  - OS information: Ubuntu 18.04.4 LTS

**Comment by ayshih** [comment]
You're confusing a number of aspects here.

> When passing the normalization from the `plot_settings` dict of a map to the plot method of another map via the `norm` keyword,

If you actually want to do this, you ought to do a (deep) copy.  There's no promise `norm` won't be modified, and in this case it is, so of course it's going to affect the first map.

> the new norm is ignored

The new `norm` is not actually being ignored.  The normalizer from the first map does not have `vmin` and `vmax` explicitly set.  So, plotting the second map with the normalizer of the first map doesn't actually carry along the range information.

> and the original normalization is modified in place such that the original map has the normalization of the new map.

For some reason, once you specify the normalizer in this manner, *then* it hardcodes `vmin` and `vmax` into the normalizer using the extent of the data (here, the second map).  Because you didn't pass a deepcopy, you have now also modified the normalizer of the first map.

I don't know why the normalizer gets `vmin` and `vmax` hardcorded, but this may be an upstream quirk.

If you had explicitly specify the `vmin` and `vmax` within the normalizer for the first map, everything would behave the way you expect.
