### ISSUE TITLE
Should remote data manager namespace file names?

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#3908]
While working on sunpy/sunxspex#34 I thought, "what would happen if two affiliated packages both used the same name for a data file?" So I was wondering if we could do some mad introspection stuff to automatically namespace variables so it would be `"sunxspex.xray_abundancies"`?

**Comment by vn-ki** [comment]
I had thought about this during the initial development and thought I could use the function path + file name (`module.sub.funcname.file`) as the key in the data manager.

The method to get the function name of the callee from the called function turned out to be implementation dependent (cpython vs others), so I abandoned the idea.

Using just the module name might be easier(?).

**Comment by dpshelio** [comment]
What if they are the same file! Do we need then to download it twice?

**Comment by vn-ki** [comment]
IIRC, they won't download twice because we have a cache which handles the downloads for data manager. I'll have to check to confirm though.

**Comment by Cadair** [comment]
I think as it's user facing name the module name + filename would be the best option.

**Comment by adwaitbhope** [comment]
If this feature is still required, can I take it up?

**Comment by nabobalis** [comment]
I don't see why not.

**Comment by adwaitbhope** [comment]
This is turning out to be more complicated than I expected. Can someone help me with the following scenarios?

1. Suppose module `A` downloads a file and it gets namespaced as `A.test_file`. Later, module `B` also wants to use the same file. This time, `DataManager` will not download it again because `cache` is keeping track of downloads. While accessing this file  (using `manager.get()`) from `B`, how can we retrieve something that is namespaced with `A`? Would we need a different DB schema that can handle this?
2. Even if this happens, will integrity be maintained now that module `B` is using a file namespaced as `A.test_file`?

**Comment by nabobalis** [comment]
It's been a while since I looked at the "DataManager", is it not storing the id of the file (that is what get uses?) and then the filepath to get to the file?

**Comment by adwaitbhope** [comment]
It does, but not in the SQL storage - the id to path mapping is stored in a `dict` in memory.
I'll try modifying this `dict`, I think that should do.
