### ISSUE TITLE
Make a policy for the minimum version of Astropy that we will support

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#3918]
We should define a policy for the minimum version of Astropy that we will support for each future SunPy release (e.g., latest LTS, N versions back, ...).  We need to consider our release schedule versus Astropy's release schedule.

(See #3154, where we don't actually know when Astropy v3.2+ will become the minimum version.)

**Comment by Cadair** [comment]
My vote would be either the newest stable version 12 months ago or previous 2 releases. Pinning to a LTS is troublesome because of our out of phase cycles.

**Comment by dstansby** [comment]
For an example of a minimum version policy, see https://matplotlib.org/devel/min_dep_policy.html. Since astropy release a LTS every two years, supporting astropy latest LTS versions upwards seems like one sensible option.

**Comment by Cadair** [comment]
There is also NEP 29 https://numpy.org/neps/nep-0029-deprecation_policy.html we could adopt which in that we could take all our minimum versions to be 24 months like it suggests for Numpy. Although it should be noted that Astropy effectively provides our minimum numpy requirement (as they are often newer than NEP 29 especially for their LTS releases (so the min numpy version isn't 4 years old by the end of their LTS cycle).

I am for the record a hard -1 on supporting the last Astropy LTS release, we are too tightly coupled to Astropy to be using something which is potentially (due to phase issues) 30 months old.

**Comment by Cadair** [comment]
(I am also kind of +0 on a SEP for this, but I am open to what others think on that)

**Comment by dstansby** [comment]
Also +0 for a SEP. In the meantime, for sunpy 2.1 I propose we specify astropy >= 4, will have been out for 1y when sunpy 2.1 is released hopefully and is a LTS.

**Comment by Cadair** [comment]
We appear to have adopted a "bump it by a version" each release and master has already been bumped to 4.0. This does kind of get a little sticky with the super delayed 4.1 release, but otherwise I am pretty happy with the emergent status quo. Perhaps we should write it down.

**Comment by ayshih** [comment]
> master has already been bumped to 4.0

Which reminds me that we should make some progress on #4000, although none of the stuff identified has any real benefit to users.

**Comment by ayshih** [comment]
For the record:

- 2.0 depends on Astropy 3.2
- 2.1 depends on Astropy 4.0

If we continue this way,
- 3.0 can depend on Astropy 4.1

**Comment by dstansby** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/5365
