### ISSUE TITLE
Write example showing how to get GOES event list

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#3942]
As discussed at the developer meeting, `get_goes_event_list` should be deprecated and removed, and a gallery example should be added showing how to get the event list using HEK.

**Comment by samaloney** [comment]
Do they actually return the same list?

**Comment by dstansby** [comment]
`get_goes_event_list` directly calls the HEKClient, so I would guess yes.

**Comment by wtbarnes** [comment]
We should think about #2434 when replacing `get_goes_event_list`. From the discussion on that issue, it seems like it may be worth querying other sources of data for the GOES event list mainly due to the response time of the HEK.

I've never actually used GOES data so I'm a bit out of my depth here, but would it be worth including queries to other sources here other than the HEK? I think we already have a HELIO client which @dpshelio mentions as another possible source of this data.
