### ISSUE TITLE
Re-projection of LASCO images

### ISSUE THREAD

**Issue by wafels** [sunpy/sunpy#3997]
### Description

It would be nice if SunPy could re-project LASCO images from different points of view.  A fundamental issue here is you have to make an assumption about where the off-solar surface material is in space.  One assumption is to assume that the LASCO image represents a plane in space perpendicular to the observer going through the center of Sun.  Another possible assumption (brought up by ayshih) is that the off-solar surface material lies on a sphere centered at the observer that passes through the center of the Sun.

### Additional context

Use cases for this functionality include being able to visualize LASCO and STEREO COR data from each other's POVs.  Further extensions of this functionality would be to visualize and re-project off disk data in general, for example STEREO HI1, HI2 and PSP WISPR data.

**Comment by ehsteve** [comment]
This sounds like a terrible idea to me given that you'd have to inject some major assumptions about the three-dimensional nature of the structures in LASCO images. You might argue that we already do this for the low-corona in EUV images but you can see through so much more once you are above the solar limb.

**Comment by ayshih** [comment]
As you say, the default assumption is already not correct (especially for, say, a halo CME), so this would just be a different assumption.  If you haven't already looked at it, #4003 implements this as a context manager, so it'd be an active choice by a user that they are using this different assumption.  (I'll point out that a user can't "do this themselves" by just manually specifying fully 3D coordinates because you need to affect how the `reproject` machinery works.)  Here are example images from that PR (I particularly like the lower-left panel of the AIA set):

![screen](https://user-images.githubusercontent.com/991759/78792054-a20fb500-797e-11ea-8b28-a2a91eb6392e.png)

![lasco](https://user-images.githubusercontent.com/991759/78804316-fd956f00-798d-11ea-9d18-58bbdaac9e72.png)

**Comment by ehsteve** [comment]
The AIA one is cool. I just don’t think that anyone in their right mind should try to infer 3D structure from only an image without it being driven by an eruption model which goes beyond what is being described for this machinery. This is not my area of expertise so perhaps there are “default” ways of doing this accepted by the commmunity and with limitations that are understood that SunPy could support. I’ve never seen it myself though. I think we need an expert to weigh in here.

**Comment by ayshih** [comment]
Closed by #4003
