### ISSUE TITLE
Slow fetch test for the SUVI client

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sunpy#4099]
When running this (https://github.com/sunpy/sunpy/blob/214920bc48d366ca6168d42b1ad6828ba458b078/sunpy/net/dataretriever/tests/test_goes_suvi.py#L85) test which does one network call via the search, the test took 10 seconds locally for me.

Is this our client code or the sever?

**Comment by abhijeetmanhas** [comment]
I tested on my system, it in total took 8 seconds. With
* Search takes 3.1 seconds
* Creating mock object takes 2.9 seconds
* fetch taking 2 seconds.

 At root of everything, in creating mock object, we do call `_get_url_for_timerange()` which is takes most of the time, also called in search. It uses scrapers `filelist`, which is called six times because of this https://github.com/sunpy/sunpy/blob/214920bc48d366ca6168d42b1ad6828ba458b078/sunpy/net/dataretriever/sources/goes.py#L287, each call takes approx 0.5 seconds. I went on further. In scraper, opening the url and finding all hrefs takes 0.3 seconds approx. 
Seems to me that it is less of a server problem, the best thing we can do is to specify a wavelength in query to reduce time six folds.

**Comment by abhijeetmanhas** [comment]
https://github.com/abhijeetmanhas/sunpy/blob/minorfix/sunpy/net/dataretriever/tests/test_goes_suvi.py#L94-L97 this reduced the test time to approx 1.5 -2 secs Instead of 8-10 seconds. 
@nabobalis should I create a PR for this or should we keep test as it is?

**Comment by nabobalis** [comment]
Sure open the PR.
