### ISSUE TITLE
More tests for submap/draw_rectangle

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4190]
From @dstansby's comment in #4175 regarding #3677, 

> Add more tests to get patch coverage to 100% (see https://codecov.io/gh/sunpy/sunpy/compare/ead9cd3c62741aaa15b35d0e836c491fc38795a0...1a3b4ac6620f794b5289bbc7c741f8081da46d07/diff)

**Comment by wtbarnes** [comment]
I've milestoned this for 2.0 but we should be very OK with bumping it.

**Comment by abhishekpandey1880** [comment]
I am intrested in this issue. Please can anyone provide some details about this issue like which file(s) to be modified and what to be checked?

**Comment by nabobalis** [comment]
I think there isn't that much left to do according to codecov. 

But based on https://codecov.io/gh/sunpy/sunpy/src/master/sunpy/map/mapbase.py#L1933 it looks like there are two blocks of code that we don't test for. 

But lines 1935 to 1937 (I have my doubts about this section) and line 1952 do not register as tested and would need to have tests added to https://github.com/sunpy/sunpy/blob/master/sunpy/map/tests/test_mapbase.py in order to resolve this.

**Comment by jeffreypaul15** [comment]
After draw_rectangle was re-written is this still the case? If yes, then can I write these tests?

**Comment by nabobalis** [comment]
Yeah this looks to be solved now looking at codecov.
