### ISSUE TITLE
Document how to copy a map

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4259]
Would be nice to be able to create copies of maps, e.g. sometimes I want to modify a map, but also keep a copy of the original hanging round. In my head this is just a case of copying the data and header and putting it in a new `Map`, but I'm sure it's more complicated (and there are other considerations as to whether this should be implemented)

**Comment by ayshih** [comment]
Do you want such a `.copy()` method to do something different than calling `deepcopy()` on the `Map`?

**Comment by dstansby** [comment]
I didn't realise one could do `deepcopy()`, thanks! No, I guess a deepcopy would be what I'd expect, but I suppose `copy()` is a more user-friendly method?

**Comment by lzivadinovic** [comment]
My 2 cents is that more pythonic way is to call `deepcopy()` because with `.copy()` method you will try to override something that is already built in into language and really generalized (it just creates copy of whatever python object you want). So i guess there is no need to write wrapper around something that is build in and straight forward.

I mean, if there is no extra task that should be done `deepcopy()` sounds like reasonable solution. And btw first hit on google for `how to make copy of python object` is differences between deep and shallow copy and how to use it with examples so it easy to look up.

**Comment by dstansby** [comment]
Sounds good - I guess it would be good to add a bit of documentation to the sunpy docs (https://docs.sunpy.org/en/stable/guide/data_types/maps.html) explaining how to copy a map (using `deepcopy`) then.

**Comment by chouhanaryan** [comment]
Hi, if this is still open can I take it up? I've already created a draft of what could be added to the docs but I'm unable to set up Sphinx locally to test my changes. Any tips on how I go about it?
I tried running `make.bat html` and `make.bat dirhtml`, but it doesn't seem to be working (a lot of errors come up and the process just exits) - am I missing something?

**Comment by nabobalis** [comment]
This should still be open, I am personally not aware of a pull request that closed this.

We have two guides on how to get setup: https://docs.sunpy.org/en/latest/dev_guide/newcomers.html#setting-up-a-development-environment and https://docs.sunpy.org/en/latest/dev_guide/documentation.html#sphinx

**Comment by chouhanaryan** [comment]
Hi! Thank you for your prompt reply. I went through the docs and ran `tox -e build_docs`, `tox -e build_docs -- -aE`, and `make html` - but I got the same error in all three. Does this have anything to do with the fact that I'm not in a conda environment by any chance?

![image](https://user-images.githubusercontent.com/46817791/93016872-f0864700-f5e1-11ea-8c9f-aaf32e9eaf23.png)

**Comment by nabobalis** [comment]
Ah, you are hitting that error. I had assumed it was a setup issue. 

That is a current bug that will be fixed by https://github.com/sunpy/sunpy/pull/4466.
It is not an issue with your setup.
