### ISSUE TITLE
Discussion on how we support GOES-XRS Data

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#4389]
This issue is for discussing the larger problem of how best to support both querying and loading GOES XRS data. We have a lot of PRs and issues related to this larger issue and so this (meta) issue just serves to try coordinate all of these efforts as best we can and come up with a coherent plan of how best to tackle this. 

Currently, `XRSClient` queries data from the SDAC (https://umbra.nascom.nasa.gov/goes/fits). The data are provided in FITS files and go up to GOES-15.

However, as pointed out in #4173, GOES-15 is no longer operational and is superseded by GOES-16 and GOESS-17. The new 16 and 17 data, however, are in netcdf format and we currently have no way of reading netcdf files in sunpy.

To further complicate things, as discussed in #4376 the data from GOES-13 through GOES-15 have been re-calibrated so as to match the calibration in GOES-16 and 17. This newly calibrated data, also only available in netcdf, significantly changes things like flare classification which is based on the peak GOES flux. We probably want to return the netcdf data with the new calibration by default. We should also still consider providing access to the older (GOES-15 and below) FITS data with the old calibration so that users can produce past results. At the very least, this will require a deprecation period.

In addition, PR #4359 adds support for GOES XRS JSON files that are provided by NOAA which seem to be quick-look data products from GOES-15 and 16 for 6 hour, 1 day, 3 day, and 7 day averages. I'm not quite sure how these data differ from those provided by the FITS or netcdf files or whether we should even support them at all if they can be derived easily from the data provided by the netcdf files.

## Primary Questions

* What is the canonical data product for GOES XRS? (FITS? JSON? netcdf?)
* What is the best way to support netcdf files in sunpy?
* By default, what do we return when a user makes a query for XRS data?
* Should we support querying and/or loading the longer time-averaged JSON files?

## All the Relevant Issues and PRs

* #3337
* #4173
* #4346 
* #4359 
* #4376

**Comment by ayshih** [comment]
> In addition, PR #4359 adds support for GOES XRS JSON files that are provided by NOAA which seem to be quick-look data products from GOES-15 and 16 for 6 hour, 1 day, 3 day, and 7 day averages. I'm not quite sure how these data differ from those provided by the FITS or netcdf files or whether we should even support them at all if they can be derived easily from the data provided by the netcdf files.

I may be mistaken, but my understanding is that those JSON files through NOAA SWPC are "operational-quality" data rather than "science-quality" data.  They have not undergone the same level of calibration and validation as what is found in the science NetCDF files.

**Comment by Cadair** [comment]
My initial reaction to some of the questions, mostly based on the community meeting yesterday:

> What is the best way to support netcdf files in sunpy?

Given we are clearly in a position where making it easy for users of our library to load data provided in netCFD we should add a dependency on a netCDF library. From the discussion at the community meeting, [h5netcdf](https://github.com/shoyer/h5netcdf) gets my vote as the library because at least then it's a common c-lib (hdf5) rather than an uncommon one (netCDF). I think we are going to have to make this an optional dependency, which is going to be a first for us (optional dep to use a timeseries or map source) so we are going to need to document and handle that in a way which makes it easy for users to understand.

That being said, there is an option 2 here. All our requirements on netCDF are goes. We could create a goes specific package and move all the map and timeseries sources in there along with `instr/goes`. I vaguely recall from previous discussions that we are unlikely to get any buy-in from the XRS / SUVI teams on this?

> By default, what do we return when a user makes a query for XRS data?

We should always be providing the highest quality science data that is available. So for XRS it looks like the netCDF files.

> Should we support querying and/or loading the longer time-averaged JSON files?

Based on my current understanding I would say these don't really belong in core, happy to be convinced though. That being said, where else do they belong?

**Comment by samaloney** [comment]
I think it's important to note the files on https://umbra.nascom.nasa.gov/goes/fits have been processed/altered ([here](https://umbra.nascom.nasa.gov/goes/fits/goes_fits_files_notes.txt)) to correct some issues e.g the times are changed to be bin centre.

I think the canonical data sources are https://www.ngdc.noaa.gov/stp/satellite/goes/dataaccess.html up to GOES-16 and then the new goes-r series https://www.ngdc.noaa.gov/stp/satellite/goes-r.html which both have netCDF files.

The application of the scaling factors to the X-ray flux data has always been an issue and I guess with the rescaling of GOES-13 to GOES-15 might make this better or worse. I think there is enough complexity and specific stuff to warrant a goes package at least for some aspects.

**Comment by wtbarnes** [comment]
#4394 addresses questions 1 and 3

**Comment by hayesla** [comment]
In regards to 2. _What is the best way to support netcdf files in sunpy?_ do we have any preference on this?

For the updated XRSTimeSeries to read the netCDF files we can either just have say `xarray` imported in `https://github.com/sunpy/sunpy/blob/master/sunpy/timeseries/sources/goes.py` and then read in - but then the `source` will need to be defined by the user and not identified through the factory - or probably the way to go is to have the netCDF reader within `sunpy/io/file_tools.read_file()`

**Comment by hayesla** [comment]
maybe I'll make a WIP PR with the timeseries updated to iterate on this

**Comment by hayesla** [comment]
I think that this can probably be closed now given #4592 and #4394
