### ISSUE TITLE
32 bit tests failing

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4406]
The 32 bit tests are currently failing, due to a failed attempt to install the `cryptography` library from source. See e.g. https://dev.azure.com/sunpy/sunpy/_build/results?buildId=9154&view=logs&jobId=a7b3aa55-7d57-562f-3433-7f6b2d4252da&j=2920fa54-56c6-5dfd-d3d8-7b1b694d90cb&t=bba4d609-c264-5f9c-e072-020a8a3b573f

**Comment by nabobalis** [comment]
My interpretation of the issue is as follows:

"cryptography" is looking for `SSL_OP_NO_DTLSv1_2`, `SSL_OP_NO_DTLSv1`, `X509_CHECK_FLAG_ALWAYS_CHECK_SUBJECT` and `X509_CHECK_FLAG_MULTI_LABEL_WILDCARDS`.

The first two are not defined in openssl 1.0.1 (https://github.com/openssl/openssl/blob/OpenSSL_1_0_1e/ssl/ssl.h) but are defined in openssl 1.0.2 (https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl.h).

The issue is that the linux image used for the 32bit image is manylinux 2010 which installs version "1.0.1e" of openssl. The current version of cryptography is only tested against ,OpenSSL 1.0.2-latest, OpenSSL 1.1.0-latest and OpenSSL 1.1.1-latest and will soon drop support for 1.0.2.

We either figure out what version of cryptography to pin for in the 32bit build so it works again or we update the 32bit image used.

**Comment by nabobalis** [comment]
cryptography 2.9.2 being the version we pin to.

**Comment by Cadair** [comment]
How about jumping back to `manylinux1` on the 32bit build?

**Comment by nabobalis** [comment]
What version of openssl does it use?

**Comment by nabobalis** [comment]
It seems they don't provide any 32bit wheels for linux anymore:
https://pypi.org/project/cryptography/#files

**Comment by nabobalis** [comment]
Since we have to compile it from source, we should just see about pinning its version for the 32 bit build.

**Comment by nabobalis** [comment]
I pinned it in tox here https://github.com/sunpy/sunpy/pull/4388
