### ISSUE TITLE
How to handle broken or missing metadata

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4410]
https://github.com/sunpy/sunpy/pull/4391 has spawned discussion on how we handle missing or broken values in FITS headers.

Stepping back another level, there seem to be three players in the game. 1. The data provider 2. sunpy and 3. a solar physicist (end user). In an ideal world, sunpy and the end user would like the data provider to provide fully FITS compliant data.

The question though is what should sunpy do when the provider provides non-FITS compliant data? Within this scenario there are two possibilities, and for each I have provided proposals for what sunpy should do:

1. We can cross check missing/non-standards compliant data against other information in the header This includes e.g. changing `cunit` from `degree` to `deg`, fixing `ctype` based on comments in the header.

In this case we have a way to know what we are doing is correct, and I propose for the purposes of not spamming the user with lots of warnings we silently fix these keywords.

2. We have to 'blindly' make an assumption, because there is no other information in the header to cross check against This includes e.g. setting `cunit` to `arcesc` if it is missing.

In this case we do not know what we are doing is always correct. I propose that we do not allow this, and the map will naturally error on a missing piece of metadata. This may be a pain for users, but if a data provider does not provide enough information to interpret a map then I do not think we should be responsible for fixing that. 

With these two proposals, no warnings are thrown, and a map is either silently loaded and fixed, or code errors. Thoughts?

**Comment by ayshih** [comment]
I feel a major reason why this is complicated is that SunPy is wearing two hats here, which do not have fully compatible interests:

- SunPy provides underlying core functionality for developers (the `Map` class and the reading of FITS files)
  - This functionality is not *directly* used by the typical end-user (the `Map` class factory doesn't count)
  - The presumption for core functionality ought to be that the FITS file is compliant with standard (or pseudo-standards)
  - Fixes that require assumptions should be avoided unless glaringly obvious, with the raising of warnings and errors being natural to facilitate software development and debugging
- SunPy provides instrument-specific handling of FITS files (e.g., `AIAMap`), which arguably is not "core" functionality
  - This functionality is what the typical end-user experiences
  - The instrument team ought to have blessed the approach for converting its FITS files to usable `Map` classes
  - From that perspective, raising warning or errors has zero or even negative value for the end-user when fixing known issues in the FITS files, even ones that may require wild assumptions, because those assumptions have been blessed by the instrument team

As I've expressed before, I think SunPy should be pushing stuff like `AIAMap` out of the core library (i.e., so SunPy wears only the first hat), and then @dstansby 's recommendation would be the natural way to go.

**Comment by wafels** [comment]
@ayshih so move `AIAMap` to `AIApy` ?  Any `AIApy` developers on this thread?  I wonder if they see any advantages to this suggestion.

**Comment by wtbarnes** [comment]
> @ayshih so move `AIAMap` to `AIApy` ? Any `AIApy` developers on this thread? I wonder if they see any advantages to this suggestion.

I don't know if we want to open this can of worms here. I know we went back and forth on this a lot at the dev meeting back in March.

I'm not entirely opposed to this and I think in theory it is probably a good idea. It makes sense to have the AIA team oversee. But I'm not sure about the reality of every person who installs sunpy who wants to look at AIA data having to install `aiapy`. For one, it scares me that that many people would depend on aiapy 😅 (mostly joking here),  but it also would just be inconvenient to have to install another package just to be able to load AIA data.

**Comment by wafels** [comment]
I've used `Map` with data that is not explicitly supported by SunPy.  Usually the maps are not nice looking, but they load.

I think you're right that this can of worms should be opened elsewhere.

**Comment by ayshih** [comment]
Okay, I've created a new issue (#4458) so we don't need to continue here on the tangent of kicking `AIAMap` out of SunPy core.

**Comment by ayshih** [comment]
For this issue in specific, perhaps the right approach is to embrace the two hats: how about if `GenericMap` is super-strict and standards-compliant with metadata, and classes like `AIAMap` contain all of the assumptions and do all of work to clean up the metadata so that `GenericMap` doesn't error?  That way, anyone creating a new `Map` subclass would have all of the benefit of strict metadata checking, and users wouldn't be negatively impacted at all if they are using a polished subclass.

**Comment by ayshih** [comment]
If that model is followed, each instrument-specific class could simply have a section in its docstring that lists explicitly all of the metadata assumptions/fixes that that class makes rather than emitting warnings.
