### ISSUE TITLE
The 'Creating a Composite map' example in the gallery shows warnings

### ISSUE THREAD

**Issue by chouhanaryan** [sunpy/sunpy#4490]
### Description
The code outputs in the [Creating a Composite map](https://docs.sunpy.org/en/stable/generated/gallery/map/composite_map_AIA_HMI.html) example in the gallery might be bugged.

### Expected vs Actual behavior
The code in the example should show appropriate outputs, but it currently doesn't.

Edit: Well, the code actually runs correctly (just ran it locally), but a number of `SunpyUserWarnings` and `FITSFixedWarnings` pop up. Is this expected behaviour?

**Comment by ayshih** [comment]
In short, the warnings are ignorable.

The `FITSFixedWarning` warnings are expected because the HMI header makes use of a non-standard `'nan'` value (see #4324).  If you want to stop the warnings, you can add the lines:
```python
hmi_map.meta['crder1'] = 0
hmi_map.meta['crder2'] = 0
```

The `SunpyUserWarning` warnings are arguably a bug.  We emit a warning when it looks like the user may be supplying a rectangle incorrectly, in this case for the `.submap()` call.  However, the check is performed in pixel space (see #4179, ping @dstansby), and doesn't currently take into account that map may be rotated.  HMI maps are ~180 degrees rotated (i.e., basically upside down), so the check incorrectly fails.  You can de-rotate the HMI map with the line:
```python
hmi_map = hmi_map.rotate()
```
I should point out that while this line will prevent the `SunpyUserWarning` associated with the `.submap()` call, the `.rotate()` call itself will emit a different `SunpyUserWarning` because HMI maps have NaN values that aren't allowed with the default rotation settings.
