### ISSUE TITLE
Sunpy 2.0.2 header duplicated in changelog

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#4508]
https://docs.sunpy.org/en/stable/whatsnew/changelog.html
![Screenshot 2020-09-28 at 11 50 25](https://user-images.githubusercontent.com/6197628/94423654-df603d00-0180-11eb-98b8-7c2db1d59327.png)

Not a massive issue, but should probably fix before the next release.

**Comment by nabobalis** [comment]
I wonder how that happened.

**Comment by Cadair** [comment]
This smells like the dev changelog code running on a release?

**Comment by hrs2203** [comment]
Hi @dstansby  , @Cadair , @nabobalis, I was trying to fix this on a local copy but was unable to generate docs. it was giving ssh error, access denied to port 443, is this something to be expected or its a mistake on my side.

**Comment by nabobalis** [comment]
Can you provide an error log? I don't have enough information to have a guess.

This issue is tricky since I am under the impression this only happens on readthedocs which most people can't access directly. If we can replicate it on our continuous integration that would be helpful.

However I would strongly recommend looking at another issue.
