### ISSUE TITLE
Need example of how to use xlim, ylim when plotting with WCS axes

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#4735]
### Description
I always have to think twice (thrice) when using `ax.set_xlim` and `ax.set_ylim` with plotting with maps and WCSAxes, and it's not really that straight forward.

An example of this would be good to include - I'll make a PR now unless it exists somewhere? (I dont think so).

Also is this the easiest way to do it? i.e. find pixel coordinates and use those or is there some WCSaxes magic to do `transform=` or something?

```python
xlim = [-500, 500]*u.arcsec
ylim = [-800, 800]*u.arcsec

limits = aia_map.world_to_pixel(SkyCoord(Tx=xlim, Ty=ylim, frame=aia_map.coordinate_frame))
...

ax.set_xlim(limits.x.value)
ax.set_ylim(limits.y.value)

```

**Comment by dstansby** [comment]
(sorry I'm repeating stuff you already know here!)

Whenever a map is plotted, the x/y axes that Matplotlib (and therefore `set_{x,y}lim`) uses are always pixel axes. On top of that, `WCSAxes` then "decorates" the axes with the world coordinates and coordinate grid. Because in the general case there is an arbitrary non-linear transformation between pixel and world coordinates, it's not (in general) possible to set plot limits with world coordinates.

In practice though, world and pixel coordinates are often aligned, so one can effectively work out limits by transforming world coordinates to pixel coordinates, which is what you're doing. As far as I know your code snippet is the best way to do this.

I agree that an example explaining the above, and having your code would be great 👍

**Comment by Cadair** [comment]
Putting my wcsaxes :tophat: on for a moment.

I feel like there is no reason why *in theory* wcsaxes couldn't do something to make this easier. I do wonder if you could either define the x limits along the x spine (i.e. you give it two 2D coordinate points which it uses to crop the x axis) and then do the same for the y axis, or you could do a similar rectangle like API to submap to crop the box based on showing all for corners.
