### ISSUE TITLE
Figure tests are affected by failures of other figure tests

### ISSUE THREAD

**Issue by ayshih** [sunpy/sunpy#4894]
This is almost certainly an upstream bug in `pytest-mpl`, but I'm logging it here until that's confirmed.

When a figure test has created a figure but does not complete due to raising an error, the next figure test run in the same run may use the partially created figure for the hash, and thus fail.  Since the false failure depends on the first figure test raising an error, this is only a critical issue if the first figure test has been marked with `xfail`.  However, it can still be annoying when developing since figure tests that shouldn't be failing can fail.

**Comment by Cadair** [comment]
This section of the pytest-mpl code should be put in a try...finally block to ensure that https://github.com/matplotlib/pytest-mpl/blob/master/pytest_mpl/plugin.py#L579 is always called.

**Comment by dstansby** [comment]
I think the better long term fix is to have `pytest-mpl` control the figures being plotted. By this, I mean that `pytest-mpl` should create the `Figure` object, and test functions should accept it as a parameter. This way reduces the chance for bugs like this to happen because of pyplot being used, and is how the matplotlib image tests work.

**Comment by Cadair** [comment]
Feel free to open an issue for that on pytest-mpl as well, I can see the advantages.

**Comment by ayshih** [comment]
With #4969, figures left on the pyplot stack are now cleared in each test's teardown.  Closing.
