### ISSUE TITLE
Move custom timeseries plotting from from peek to plot

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunpy#5066]
Related to #5058 move custom timeseries plotting from from peek to plot and then have peek call plot. Check and update docs as needed.

Okay, I've made the changes that I wanted.  I didn't update the `peek()` docstrings for the derived TimeSeries classes because their implementations needs to be cleaned up (i.e., source-specific plotting code should be accessible through a `plot()` method, but is only found in the `peek()` method).  I think such changes should be put off to a different PR.

_Originally posted by @ayshih in https://github.com/sunpy/sunpy/issues/3103#issuecomment-494839081_

**Comment by jeffreypaul15** [comment]
Would we want the `peek()` and `plot()` methods to be producing the same plot right?
Doesn't peek already call plot? Can I get a bit more insight on this?

**Comment by ayshih** [comment]
While there is no design document, the general notion – at least for `Map` – has been that `peek()` is a more specialized version of `plot()`.  `plot()` is intended for all matplotlib workflows, whereas `peek()` is for someone who may wish to avoid calling any matplotlib commands directly.  So, fundamentally, the `peek()` methods should contain a `plot()` call plus a handful of additional matplotlib commands for a "nice" default look to the plot.  For example, `Map.peek()` always adds a colorbar, but the `plot()` method does not.

However, the `TimeSeries` classes don't follow that model.  Sources aren't overriding the inherited `plot()` method from the base class, so the only way to get source-specific plotting (e.g., units, labels, colors) is to use the `peek()` methods.  So, the first step is to move most of each source's `peek()` code to a corresponding source-specific `plot()` method, and make `peek()` mostly a wrapper to `plot()`.  Some thought ought to go into what parts of the existing `peek()` formatting should not always be done and hence should stay in `peek()` rather than `plot()`.

As an aside, I'll note that we have repeatedly failed to achieve consensus on exactly what `peek()` should do.  If you put in a PR for this issue, don't be surprised if trigger a fresh round of debate on `peek()`.  Regardless, it's clear that these classes need proper `plot()` methods.

**Comment by jeffreypaul15** [comment]
> While there is no design document, the general notion – at least for `Map` – has been that `peek()` is a more specialized version of `plot()`. `plot()` is intended for all matplotlib workflows, whereas `peek()` is for someone who may wish to avoid calling any matplotlib commands directly. So, fundamentally, the `peek()` methods should contain a `plot()` call plus a handful of additional matplotlib commands for a "nice" default look to the plot. For example, `Map.peek()` always adds a colorbar, but the `plot()` method does not.
> 
> However, the `TimeSeries` classes don't follow that model. Sources aren't overriding the inherited `plot()` method from the base class, so the only way to get source-specific plotting (e.g., units, labels, colors) is to use the `peek()` methods. So, the first step is to move most of each source's `peek()` code to a corresponding source-specific `plot()` method, and make `peek()` mostly a wrapper to `plot()`. Some thought ought to go into what parts of the existing `peek()` formatting should not always be done and hence should stay in `peek()` rather than in `plot()`.
> 
> As an aside, I'll note that we have repeatedly failed to achieve consensus on exactly what `peek()` should do. If you put in a PR for this issue, don't be surprised if you trigger a fresh round of debate on `peek()`. Regardless, it's clear that these classes need proper `plot()` methods.

Ah, I see. Hopefully I shall open a PR addressing this. Thanks!
