### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by AlucardmaI** [sunpy/sunpy#5280]
It might be a stupid question but I am having a hard time running this code:

```idl
wdir5='/home/udis/Task/Data/'; choose the right folder

uu=file_search(wdir5)

for i=0,n_elements(uu)-1 do begin

  wdir=strjoin([string(uu[i]),'/'])

restore,wdir+'Jz_2011-02-15T013412.sav'

nnn=size(jz)

file=file_search(strjoin([string(wdir),'*Bp*.fits']))
read_sdo,file,index_Bp,data_Bp,/uncomp_delete

nnn1=nnn[1]
nnn2=nnn[2]

help,nnn1,nnn2

;lie=nnn1/12
;hang=nnn2/8

lie=nnn1/4
hang=nnn2/4
```
I keep getting a syntax error
![Untitled](https://user-images.githubusercontent.com/83465494/116725478-2d4f5480-a99f-11eb-9c94-46fb5eb7c649.png)

**Comment by nabobalis** [comment]
Hi @AlucardmaI, two things.

1. Could I see any more of the error traceback you got from running that code? A syntax error isn't enough to work out what could be the problem here.
2. That is IDL code and not quite within our realm here. While we do have people who work with IDL, we generally don't provide support for IDL problems.

**Comment by nabobalis** [comment]
If you have any updates on this, please reopen the issue.
