### ISSUE TITLE
Make a bot to automatically rename changelog files

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5415]
It's a bit tedious to write some code, commit, open a PR, and then have to go back to rename the changelog entries to match the PR number after the PR has been opened. Instead it would be super nice if we had a bot that automatically renamed newly added changelog entries of the form `xxxx.breaking.rst` etc. to the correct PR number once the PR had been opened.

**Comment by ayshih** [comment]
Two thoughts:

- When you say `xxxx.breaking.rst` as an example, I hope you mean that the filename literally has the string "xxxx" rather than a (guess at the) number.  In rare cases, we need to update a past changelog entry in a newer PR, so I wouldn't want to fight a bot in those cases.
- I'd imagine that the implementation would have to add a commit to the user's branch.  I think less-experienced developers are always thrown a little when their online branch is moved ahead of their local branch without their action.  Granted, in this case, since the developer would need to actively name a file `xxxx.breaking.rst`, perhaps the developer documentation would just need to be crystal clear what to do immediately afterwards to re-sync the local branch.

**Comment by dstansby** [comment]
>     * When you say `xxxx.breaking.rst` as an example, I hope you mean that the filename literally has the string "xxxx" rather than a (guess at the) number.

Yes.

To throw another idea out there, to avoid updating user branches perhaps the bot could rename the file after the PR has been merged by adding a commit to the `main` branch.

**Comment by Cadair** [comment]
To be honest I would rather have a bot where you type the changelog entry in a PR comment and it adds the changelog for you. The hard part of either of these workflows is teaching the bot how to commit.
