### ISSUE TITLE
JSOCClient is retrieving data outside the time window

### ISSUE THREAD

**Issue by AKMourato** [sunpy/sunpy#5447]
Using JSOCClient to acquire data is always retrieving data outside the defined time interval.
e.g:

client = jsoc.JSOCClient()
start_time= '2011-01-13T08:15:31'
end_time= '2011-01-13T08:16:21'
client.search(a.Time(start_time,end=end_time), a.jsoc.Series('hmi.Ic_45s'), a.jsoc.Notify('xxx'))
>>>
![jsocbug](https://user-images.githubusercontent.com/47477506/124789729-7218de00-df42-11eb-813d-ef6e4d8af260.png)

**Comment by Cadair** [comment]
I suspect that this is because the HMI data are in the TAI time scale not UTC.

```
Time('2011-01-13T08:15:31').tai
<Time object: scale='tai' format='isot' value=2011-01-13T08:16:05.000>
```

You should try constructing an astropy Time object in TAI like this: `Time(start_time, scale='tai')` and then try the search with that.

Hope that helps.

**Comment by MKSK22** [comment]
Unfortunately, it doesn't solve it @Cadair. The time scale is possibly not the issue here since the time window is the same, and yet is returning data outside the 45 seconds period. Anyway I tried in TAI but the problem remains.

It's strange because this issue doesn't happen using Fido, and both collect data from the HMI.

Thanks anyway for your help!

**Comment by MKSK22** [comment]
Unfortunately, it doesn't solve it @Cadair. The time scale is possibly not the issue here since the time window is the same, and yet is returning data outside the 45 seconds period. Anyway I tried in TAI but the problem remains.

It's strange because this issue doesn't happen using Fido, and both collect data from the HMI.
The difference relies on the client used, Fido collects these specific series from the VSO, therefore I would say that there is some bug in the JSOCClient.

Thanks anyway for your help!

**Comment by MKSK22** [comment]
In addition, using **attrs.Time()** with the **near** argument does not work with JSOC client, but with VSO does.
Not sure if it was supposed to work since it is not specified in the documentation which providers support this feature but can be somewhat related to this issue.

**Comment by Cadair** [comment]
Interesting.

Firstly, I wouldn't expect the near flag to work with JSOC.

Secondly, the JSOCClient does convert start and end time to TAI before generating the JSOC recordset string. So that's worth keeping in mind.

As for why it's returning results outside of the given range I suspect that it's a quirk of the JSOC web export data service and not a bug in sunpy. To confirm that we would need to extract the generated query and see what results it returns on the web.

**Comment by wtbarnes** [comment]
It might also be worth checking what `drms` returns with an equivalent query. This would help narrow it down a bit before going straight to the web form.

**Comment by dstansby** [comment]
Doing a bit of debugging, the query being handed to drms is `hmi.Ic_45s[2011.01.13_08:16:05_TAI-2011.01.13_08:16:55_TAI]`, so it looks like it's an upstream issue in `drms`.

**Comment by dstansby** [comment]
Or maybe it isn't an upstream issue, as running
```python
from drms.client import Client


c = Client()
results = c.query('hmi.Ic_45s[2011.01.13_08:16:05_TAI-2011.01.13_08:16:55_TAI]', key='**ALL**')
print(results)
```
gives me
```
                   DATE                DATE__OBS  ...                                           CODEVER3 CALVER64
0  2012-09-05T06:22:51Z  2011-01-13T08:14:40.40Z  ...  $Id: polcal.c,v 1.4 2010/09/23 20:57:27 schou ...       16
1  2012-09-05T06:22:51Z  2011-01-13T08:15:25.40Z  ...  $Id: polcal.c,v 1.4 2010/09/23 20:57:27 schou ...       16
2  2012-09-05T06:22:51Z  2011-01-13T08:16:10.40Z  ...  $Id: polcal.c,v 1.4 2010/09/23 20:57:27 schou ...       16
```
All the DATE_OBS are within the requested range, so I wonder if it's an issue with how we are reading in these dates in sunpy.

**Comment by dstansby** [comment]
So I suspect that when a time is specified to `drms`, it is used to filter based on `DATE-OBS`, but we return `T_REC` in the results, and these two times are not the same. For the query above, here's the difference:
```
         T_REC         
-----------------------
2011.01.13_08:15:45_TAI
2011.01.13_08:16:30_TAI
2011.01.13_08:17:15_TAI
        DATE-OBS       
-----------------------
2011-01-13T08:14:40.40Z
2011-01-13T08:15:25.40Z
2011-01-13T08:16:10.40Z
```

So to make progress I think need to confirm 
- What keyword JSOC filters on when a time range is specified
- Which of the different times that `drms` returns in the query result (e.g., T_REC, DATE-OBS, maybe others?) we should be returning in the sunpy results.

**Comment by wtbarnes** [comment]
We should probably at least be returning `DATE-OBS` in the query result. I've reached out to some of the AIA folks to see if they can provide some clarity too. @mbobra maybe you have some insight on this?

**Comment by wtbarnes** [comment]
Marc Derosa linked me to Section 4.2.4 of the [SDO User Guide](https://www.lmsal.com/sdodocs/doc/dcur/SDOD0060.zip/zip/entry/):

> For HMI observables, the time contained in the T_REC keyword is offset from T_OBS by the light travel time between 1 AU and the location of SDO in its orbit. This offset is primarily due to the ellipticity of the Earth’s orbit around the sun, and thus varies on an annual basis by as much as ±8 seconds. However, this effect, if unaccounted for, introduces measurable errors in the helioseismology results. For AIA images, T_REC is the same as T_OBS after rounding to the nearest second. When querying the JSOC, users should be aware that in many cases (including queries of all dataseries listed in Table 1) it is the T_REC keyword, and not T_OBS or DATE-OBS, that is used to determine whether records fall into the time range specified in the query.
>
> The times contained in T_OBS and T_REC are tagged in either International Atomic Time (TAI) for HMI, or in UTC for AIA. The difference between TAI and UTC is due to leap seconds that have been added to UTC over the years (due to the gradual slowing down of the Earth’s rotation rate); such leap seconds have not been added to TAI. At the time of this writing, UTC lags TAI by 37 seconds, with three leap seconds occurring since the launch of SDO in 2010. These leap seconds occurred at the end of the day on 30 June 2012, 30 June 2015, and 31 December 2016.

**Comment by Cadair** [comment]
I think we use T_REC because its the most likely to be in the results.

**Comment by dstansby** [comment]
Conclusions from this weeks dev meeting:
- This is a quirk of JSOC, and it seems like for some reason they are filtering on `T_OBS` for this series, instead of `T_REC` which is what is used most of the time.
- We'll add a note about this quirk in the docs, but there's not anything we can do to fix this on the sunpy side.

**Comment by Cadair** [comment]
The specific section of the SDO users guide explaining this is: https://www.lmsal.com/sdodocs/doc/dcur/SDOD0060.zip/zip/entry/sdoguidese4.html#x9-240004.2.4
