### ISSUE TITLE
Document `_attrs_module()` method in Fido dev docs

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5565]
Originally brought up by @Cadair in https://github.com/sunpy/sunpy/pull/5558#discussion_r722124906:

> You shouldn't need to do this, you can have the client register the attrs namespace so this becomes a.cdaweb.Dataset,
like this: ... though why this isn't in the Fido client dev docs is a mystery to me.

**Comment by SauravMaheshkar** [comment]
Is this the file?

https://github.com/sunpy/sunpy/blob/a66cd925f57171a70dd6d079a7a8708c75c4c06b/sunpy/net/attrs.py#L25

**Comment by dstansby** [comment]
No, it's one of the documentation files that needs updating. I'm going to remove "Good first issue" because tackling this requires some knowledge of how`Fido` works to write the correct docs.

**Comment by exitflynn** [comment]
hi, I would very much like to work on this. However, we don't currently _have_ any documentation for writing clients that require new attrs to be made.

There's the [Extending Fido](https://docs.sunpy.org/en/latest/dev_guide/contents/extending_fido.html), but in the example there:
> As [attrs](https://docs.sunpy.org/en/latest/reference/net.html#module-sunpy.net.attrs) has [Time](https://docs.sunpy.org/en/latest/generated/api/sunpy.net.attrs.Time.html#sunpy.net.attrs.Time) and [Level](https://docs.sunpy.org/en/latest/generated/api/sunpy.net.attrs.Level.html#sunpy.net.attrs.Level) we don’t need to define any of our own attrs for this client.

Does this call for a new example? Let me know if i'm missing something.

**Comment by nabobalis** [comment]
I think this calls to showcasing how to add new Attrs subclasses that a needs client in the developer documentation.

**Comment by alasdairwilson** [comment]
So as per discussion at todays meeting, here are my thoughts on this:

 _attrs_module has a fairly simple purpose, it returns a tuple of the target namespace and the module to be imported into the namespace. e.g. 

```
@classmethod 
def _attrs_module(cls): 
     return 'jsoc', 'sunpy.net.jsoc.attrs' 
```
     
Would import all the attrs in `sunpy/net/jsoc/attrs.py` into `attrs.jsoc.__all__` but it is part of a complex class dynamic.

There is probably places which its use could be explained:

Since there is no  `_attrs_module` in the GenericClient class there is no obvious place to put a docstring but maybe it should have a code comment at:  https://github.com/sunpy/sunpy/blob/d702abe64acd563780dbf83ed7a3bc573cdf9426/sunpy/net/base_client.py#L400

Explaining that if a subclass has `_attrs_module` then this hook imports them into the attrs namespace.

In the dev guide page: https://docs.sunpy.org/en/latest/dev_guide/contents/extending_fido.html#adding-attrs-to-registry Where it should be explained that custom attrs, in their own attrs.py module can then imported to the attrs namespace using the _attrs_module class method, this could be a tiny, 2 sentence, subsection adjacent to the one I linked and then it can feature a short code block example from one of the clients, e.g. JSOC or GOES, which uses the classmethod.
