### ISSUE TITLE
`.submap()` doesn't preserve `.plot_settings['norm']`

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5667]
Creating a submap with `GenericMap.submap()` does not preserve any custom set norm (ie. `.plot_settings['norm']`) in the new map.

**Comment by wtbarnes** [comment]
Huh...but we are passing in `self.plot_settings` to `_new_instance`: https://github.com/sunpy/sunpy/blob/3da48422cf176492ffa029e09fb1d1cdbb292374/sunpy/map/mapbase.py#L1881

**Comment by wtbarnes** [comment]
I can reproduce this if the map is an `AIAMap`. This snippet gives,

```python
import sunpy.data.sample
import sunpy.map
from astropy.visualization import ImageNormalize, LogStretch
m = sunpy.map.Map(sunpy.data.sample.AIA_171_IMAGE)
m.plot_settings['norm'] = ImageNormalize(vmin=1.1, vmax=42, stretch=LogStretch())
print(m.plot_settings['norm'].vmin)
print(m.plot_settings['norm'].vmax)
print(type(m.plot_settings['norm'].stretch))
m_sub = m.submap(m.bottom_left_coord,top_right=m.center)
print(m_sub.plot_settings['norm'].vmin)
print(m_sub.plot_settings['norm'].vmax)
print(type(m_sub.plot_settings['norm'].stretch))
```

```python
1.1
42
<class 'astropy.visualization.stretch.LogStretch'>
None
None
<class 'astropy.visualization.stretch.AsinhStretch'>
```

However, in the case of a `GenericMap`, the plot settings persist past the submap call,

```python
m = sunpy.map.GenericMap(m.data, m.meta)
m.plot_settings['norm'] = ImageNormalize(vmin=1.1, vmax=42, stretch=LogStretch())
print(m.plot_settings['norm'].vmin)
print(m.plot_settings['norm'].vmax)
print(type(m.plot_settings['norm'].stretch))
m_sub = m.submap(m.bottom_left_coord,top_right=m.center)
print(m_sub.plot_settings['norm'].vmin)
print(m_sub.plot_settings['norm'].vmax)
print(type(m_sub.plot_settings['norm'].stretch))
```

```python
1.1
42
<class 'astropy.visualization.stretch.LogStretch'>
1.1
42
<class 'astropy.visualization.stretch.LogStretch'>
```

I have not tested this with other map source classes, but I suspect the results will be the same for other map classes as well. I think this is because we reset the plot settings in the constructor of the Map sources to settings that we've deemed appropriate for that source. 

I think a possible fix here to set the plot settings on the map in `_new_instance` *after* we instantiate the map, i.e. not through the constructor.

**Comment by dstansby** [comment]
Thanks for the example - I think it was an `AIAMap` that I found this issue.
