### ISSUE TITLE
[Doc] Coordinates: Observer Location Information

### ISSUE THREAD

**Issue by ZeyuSun** [sunpy/sunpy#5701]
### Description

I thought Heliographic Carrington coordinates is one of the few that does not depend on the observer, but the document says [here](https://docs.sunpy.org/en/stable/api/sunpy.coordinates.frames.HeliographicCarrington.html#sunpy.coordinates.frames.HeliographicCarrington) that it does, because "it takes into account the time it takes for light to travel from the Sun’s surface to the observer", which I do not quiet understand.

Sorry if it seems more of a physics questions rather than about the software. I thought the [document](https://docs.sunpy.org/en/stable/code_ref/coordinates/index.html#observer-location-information
) mistook Heliographic Stonyhurst for Heliographic Carrington, but it was apparently intended.

**Comment by ayshih** [comment]
Stonyhurst heliographic coordinates do not depend on the observer location.  The orientation axes depend on the locations of the Sun and the Earth, regardless of where the observer is located.

Carrington heliographic coordinates – as implemented by SunPy – depend on the observer location due to the effects of light travel time.  An observer farther from the Sun than another observer will see the surface of the Sun as emitted at an earlier time.  Our implementation enables the accurate co-alignment of images of the Sun's surface from observers at different distances from the Sun.  See [this page](https://docs.sunpy.org/en/stable/code_ref/coordinates/carrington.html) for a detailed explanation and a comparison to other resources.

**Comment by ayshih** [comment]
Weird, I have no idea why the docstring for `HeliographicCarrington` does not link to that page.  I'll fix that.

**Comment by ZeyuSun** [comment]
Thanks for the explanation! That clears up some of my misunderstandings.
