### ISSUE TITLE
GOES/XRS time issue

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#5914]
### Describe the bug

it looks like the way we currently are registering the time array for the GOES XRS data is including leap seconds, however in the data file it ignores it, meaning that the data is currently off by ~27 seconds for GOES 13, 14, 15 for the reprocessed data (as the time is calculated from seconds from 1970-01-01). Its not much of an issue for GOES 16 and 17 as the time is calculated from seconds since 2000-01-01 12:00:00 and hence there are not many leap seconds. 

it is not an issue with the older GOES files (i.e. the fits files from SDAC) see plot:

![Screen Shot 2022-02-24 at 12 23 45](https://user-images.githubusercontent.com/4620298/155515242-3eb30095-0df6-4fc6-942b-1ee6662ee91a.png)

I'll make a PR now to fix this

**Comment by ayshih** [comment]
A critical question: have you verified – e.g., through documentation – that the "seconds" counter in the newer GOES files ignores leap seconds?  I ask because it could alternatively be the case that the older GOES files – which I believe were generated by non-NOAA folks using SSW – erroneously ignored leap seconds.  That, the bug in SunPy may be with the older GOES files, not with the newer ones.

**Comment by hayesla** [comment]
yes I have - I've also tested with EVE/ESP data with the GOES proxy channel. The old files were correct. 

Similarly by testing against GOES 13, 14, 15 with GOES 16, 17 we can see that the leap seconds are ignored. For example the GOES 16 and 17 data is presented as seconds past 2000-01-01 12:00:00 whereas the GOES 13-15 are from 1970-01-01, and so for dates that have overlapping data to make the peaks match leap seconds have to be ignored if that makes sense.

**Comment by hayesla** [comment]
so like in the plot - the peak of the GOES 16 and GOES 15 should line up right

**Comment by hayesla** [comment]
it just wasn't noticeable for the GOES 16 data as there haven't been many leap seconds since 2000, hence was only picked up in the GOES 13-15 data. 

Also in the [documentation](https://data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/goes16/l2/docs/GOES-R_XRS_L2_Data_Readme.pdf) it says: Time is defined as seconds since 2000-01-01 12:00:00 UTC, neglecting leap seconds.

**Comment by ayshih** [comment]
Okay, great!

It's tangential to this issue, but there's a potential bug with the handling of certain older GOES files.  This code branch:
https://github.com/sunpy/sunpy/blob/1153d9fd12ecffd7b689e89bf63626b567172c88/sunpy/timeseries/sources/goes.py#L213-L217
may be incompatible with this later line:
https://github.com/sunpy/sunpy/blob/1153d9fd12ecffd7b689e89bf63626b567172c88/sunpy/timeseries/sources/goes.py#L221
because that addition will not be performed in `utime` space, so will not ignore leapseconds as it should.  This incorrect addition has essentially no impact if `TIMEZERO` is aligned with the start of the observation, but I don't know if that's guaranteed.  The GOES/XRS sample file doesn't go through this code branch, so its `TIMEZERO` is not used, but its `TIMEZERO` value suggests that `TIMEZERO` is not necessarily aligned with the start of the observation.
