### ISSUE TITLE
Fix tests with hypothesis 6.39

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5927]
### Provide a general description of the issue or problem.

A new release of hypothesis seems to be breaking some of our tests, e.g. see https://app.circleci.com/pipelines/github/sunpy/sunpy/16337/workflows/d7d7147c-31a7-441d-a8b1-06510052535a/jobs/75114

**Comment by ayshih** [comment]
Since the CI log will presumably go poof at some point, the errors are like:
```
_ ERROR collecting .tox/py38-figure/lib/python3.8/site-packages/sunpy/coordinates/tests/test_metaframes.py _
../../.tox/py38-figure/lib/python3.8/site-packages/sunpy/coordinates/tests/test_metaframes.py:194: in <module>
    @given(lon=longitudes(), lat=latitudes(),
../../.tox/py38-figure/lib/python3.8/site-packages/astropy/units/decorators.py:256: in wrapper
    return return_.to(wrapped_signature.return_annotation)
E   AttributeError: 'LazyStrategy' object has no attribute 'to'
```
which looks like a bad interaction between `hypothesis` and Astropy?  Can you try switching the order of these two decorators here (and 9 lines below)?
https://github.com/sunpy/sunpy/blob/3f4c2a88affe625beb096c647d44f065d580e5c0/sunpy/coordinates/tests/strategies.py#L13-L14

**Comment by ConorMacBride** [comment]
Was just in the middle of trying that.

**Comment by ConorMacBride** [comment]
The issue is only present with the pinned version of astropy for the figure tests.
