### ISSUE TITLE
Relax conditions for instantiating an `HMISynopticMap` source

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#5978]
Currently, we require that for a map to be parsed as an `HMISynopticMap`, it has to meet the condition

https://github.com/sunpy/sunpy/blob/e45b9b2bfbf38c8b800ee04b51e37d69a34df3e0/sunpy/map/sources/sdo.py#L207-L209

Checking the content string this strictly means that files like http://jsoc.stanford.edu/data/hmi/synoptic/hmi.Synoptic_Mr.2111.fits, where the `CONTENT = 'Carrington Synoptic Chart'` are not identified as synoptic maps and actually throw an exception due to the "sine latitude" unit issue (see [this chat exchange for more details](https://matrix.to/#/!MeRdFpEonLoCwhoHeT:matrix.org/$1647593477284yBRsZ:openastronomy.org?via=matrix.org&via=openastronomy.org&via=cadair.com)).

Could we relax the condition for checking `CONTENT`, e.g. `if 'carrington synoptic chart' in header.get('content', '').lower()`? Is there a particular reason to require the "Of Br Field" as well?

**Comment by dstansby** [comment]
I think changing the check as you described is a good idea 👍

**Comment by warussel** [comment]
Hello, I am new to Sunpy but I am interesting in contributing and this looks like a decent issue to start with. Would it be all right for me to work on a fix for this issue?

**Comment by nabobalis** [comment]
That would be fine.

**Comment by warussel** [comment]
Hey folks, I pushed a PR with my fix for this issue. Just two lines of code, I tested on the given sample file and several other HMI Synoptic map source files from the JSOC library. Looks like my code passes all of the pytests locally, although there was a few things I was not certain of as a new contributor:

1. Do I need to add to the changelog? If yes, is that something I should do myself or should a maintainer do for me? 
2. Do I need to explicitly ask for a review? I.e. should I add the review requested label myself? 
3. There is already a unit test for the is_datasource_for method in the pytests, since this still passes with my changes I figured I do not need to edit the existing unit tests. Is this true? 

Thanks for your help everyone, I hope this contribution is useful!

**Comment by nabobalis** [comment]
> 1. Do I need to add to the changelog? If yes, is that something I should do myself or should a maintainer do for me?

For a bugfix like this, yes a changelog is required. You can add one or you can ask a maintainter to do it for you.

> 2. Do I need to explicitly ask for a review? I.e. should I add the review requested label myself?

No, someone will come around to review the PR eventually. Unless you want someone specific to review the PR.

> 3. There is already a unit test for the is_datasource_for method in the pytests, since this still passes with my changes I figured I do not need to edit the existing unit tests. Is this true?

Ideally we would like to test this but since we are weakingthe check, I don't think it would be required.
