### ISSUE TITLE
Only support rotations when calling `GenericMap.rotate()`

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#5982]
### Provide a general description of the issue or problem.

`GenericMap.rotate()` currently accepts `rmatrix` and `scale` keyword arguments. These can both be used to modify a map in ways that are not rotations. I think this is confusing API desgin, and we should force `rotate()` to only be used for rotations. This would:

- avoid developer confusion when working with the method implementation
- avoid potential user confusion where someone sees `.rotate()` being called, but either no rotation is happening, or alongside rotation some other transformation is happening to

To do this I propose to:

1. Deprecate the `rmatrix` and `scale` keyword arguments to `rotate()`
2. Create a new method called `.linear_transform()` that supports either `matrix` input (for a custom 2x2 matrix) or `rotate` and `scale` input. Users can then use this to transform their maps, or if they are just doing a rotation use `rotate()`.

**Comment by x249wang** [comment]
Hey @dstansby, I'd like to try implementing the suggested change here :) Just want to double check my understanding - is your proposal to have `rotate` only accept a rotation angle, and have `linear_transform` work like the current version `rotate` (where it can accept an angle/rmatrix/none of the two, plus scale factor)?

**Comment by ayshih** [comment]
@x249wang: I suggest holding off on this issue until it's had more discussion.

@dstansby: Some questions:
* `.rotate()` would just be a wrapper to `.linear_transform()`, correct?  `.rotate()` would create the appropriate matrix to feed into the latter?  That is, all of the non-trivial implementation would still be in one method, just with a different name?
* Would `.rotate()` with no arguments still perform de-rotation based on the map's PCij matrix, even if that matrix is not a pure rotation?
* Would it be confusing that a user wouldn't be able to call `my_map.rotate()` using `my_map.rotation_matrix`, which is currently the only property that represents the map's rotation angle?

**Comment by dstansby** [comment]
>     * `.rotate()` would just be a wrapper to `.linear_transform()`, correct?  `.rotate()` would create the appropriate matrix to feed into the latter?  That is, all of the non-trivial implementation would still be in one method, just with a different name?
Yes, that's what I imagined.

>     * Would `.rotate()` with no arguments still perform de-rotation based on the map's PCij matrix, even if that matrix is not a pure rotation?

I would say as a rule a method called `rotate` shouldn't do anything but rotate, so no? To adequately replace the currente behaviour of `rotate()`, perhpas we could add another new method that reprojects a map into a WCS that is HPL{T,N}-TAN, has the Sun centered, and solar north pointing up. That could then be used more generally across a wide range of maps with different coordinate systems.

>     * Would it be confusing that a user wouldn't be able to call `my_map.rotate()` using `my_map.rotation_matrix`, which is currently the only property that represents the map's rotation angle?

Two things:
- (as I think you've pointed out elsewhere!) `.rotation_matrix` isn't always a pure rotation matrix...
- A map's rotation angle isn't always well defined

Perhpas the solution here is to add a new property that is the rotation angle about the reference coordinate needed to align the pixel y-axis with solar north (at the reference coordinate)? I haven't thought through whether it's *always* possible to calculate or how one would calculate this though...

**Comment by Cadair** [comment]
I am not sure I am on board with this plan, it feels like we are not really helping usability here for the sake of mathematical purity.

Being able to do `rotate()` is something we have advertised for *years* and I am not really sure what we are gaining by making everyone type `linear_transform()` instead? If someone is passing a matrix to `rotate()` they probably know if it's purely rotation or not? Or if they don't they don't care?

**Comment by dstansby** [comment]
I disagree; I think having methods that do what they say on the tin is a big improvement to usability. It's not about mathematical purity, but avoiding confusion. e.g.,

- the answer to "how do I rescale my map?" is currently "use a method called `rotate`". I think that is very unituitive and confusing. 
- if I see the code `rotate(rmatrix=a_matrix)` in isolation (e.g. in someone else's code), I'm going to assume that my map is only going to be rotated, and that rmatrix is a rotation matrix. Neither of those conditions are neccesarily true as it stands.

**Comment by Cadair** [comment]
> the answer to "how do I rescale my map?" is currently "use a method called rotate". I think that is very unituitive and confusing.

No? In isolation it's "use rescale" or "use superpixel"?

**Comment by Cadair** [comment]
> Neither of those conditions are neccesarily true as it stands.

I see your point, but is this really worth the cost? rotate has existed in it's current form for a long time, we have downstream packages using it (aiapy at minimum) this is not a trivial deprecation (especially as you are proposing to keep the method with a different signature).

**Comment by dstansby** [comment]
I forgot that `superpixel()` effectively did rescaling 👍 I don't think there's a `rescale()` method, but perhaps it would be nice to have one as a wrapper round `superpixel()` since `superpixel` didn't jump out to me as the method to use to rescale a map?

Long term I personally think it's worth the cost, but can see the argument both ways. I guess there's also the argument that we have limited developer time, and this might not be high priority.

**Comment by Cadair** [comment]
my bad, it's `resample`: https://github.com/sunpy/sunpy/blob/main/sunpy/map/mapbase.py#L1454

**Comment by wtbarnes** [comment]
I'm on board with this. I appreciate that `rotate` has been around for years and is very useful, but the nomenclature is confusing, not only because of the fact that "rotate" also scales and translates but also because (as David mentioned in another unrelated thread) "rotate" can mean a lot of different things. I've encountered more than one user who thought that "rotate" meant correcting for solar rotation (I realize we still want to have some method called `rotate`, but just wanted to make this point to say we shouldn't add to the confusion).

FWIW, in the context of aiapy, I would like to move away from using `rotate` for image registration in favor of reprojecting into a wcs with a diagonal pci_j and appropriate cdelt. See https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/merge_requests/157. The main motivator for this is to support registering submaps, which as far as I understand it, is not possible with rotate.

**Comment by ayshih** [comment]
I think I'm not on board with this.  While `rotate()` does provide more functionality than pure rotation, I don't see the harm in providing that additional functionality to users as long as as we don't do silly stuff like telling them to use `rotate()` for pure scaling when `resample()` exists.  I also don't see the reason to stop a user from calling `rotate()` with a pure rotation matrix, just because they happen to have that instead of a rotation angle.

Incidentally, what *are* the use cases for `rotate()` with either an angle or matrix argument?  I primarily use `rotate()` for de-rotation, so I don't provied the angle/matrix.  The only times that I ever use `rotate()` with an angle argument is to create a map with rotation metadata that I can then use to test de-rotation during code development.  Maybe there needs to be a new `derotate()` method!

> To adequately replace the currente behaviour of `rotate()`, perhpas we could add another new method that reprojects a map into a WCS that is HPL{T,N}-TAN, has the Sun centered, and solar north pointing up.

You'd want to write something more general, but regardless, I'll point out that reproject is more computationally intensive than a linear transformation.
