### ISSUE TITLE
Fix the conda build by installing openjpeg 2.3+

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy#6168]
The new jp2 write tests need at least version 2.3.0 of openjpeg

**Comment by ConorMacBride** [comment]
This is also an issue for the PyPI publish CI. Should this test have `@skip_glymur` instead of `@skip_windows`?

https://github.com/sunpy/sunpy/blob/276d36fb54233275c7f594c1c167c1a354ea5a45/sunpy/io/tests/test_jp2.py#L36-L45

Am I right in saying we don't install openjpeg during the publish tests or the windows tests, so these jp2 tests are skipped then?

**Comment by nabobalis** [comment]
Yeah that has the wrong skip on it
