### ISSUE TITLE
Add a map source for ISOON

### ISSUE THREAD

**Issue by MSKirk** [sunpy/sunpy#618]
Ran into troubles using maps with ISOON (Improved Solar Observing Optical Network) data. The problem stems from the fits header: solar radius is measured in pixels rather than arcsec.

Example data is here (BlueWing_HAlpha, RedWing_HAlpha, LineCenter_HAlpha and WhiteLight): http://astronomy.nmsu.edu/mskirk/

Some code exists here and we should forward port this: https://github.com/MSKirk/sunpy/commit/2c1704c2a5afcba4730f7715110acd6e6086dfcf

This will need tests, and some documentation examples.

**Comment by wtbarnes** [comment]
@MSKirk could you give this a try and see if you still run into issues with the current implementation of `Map`?

**Comment by wtbarnes** [comment]
After reading in the header and adding `cunit1` and `cunit2` entries, I was able to register your `ISOONMap` and read data into a map from one of the files you linked above (I'm impressed that your UNM site is still up! 😆). However, the header still seems a bit wonky as it is falling back to a simple WCS because it can't parse one from the header see https://github.com/sunpy/sunpy/blob/ffce1d0381f14189292cfad90af7573fd5cf8e79/sunpy/map/mapbase.py#L277

Also, I'm a bit confused as one of the comments says the 'crval' entries are in pixels? 

```
CRVAL1  =              0.00000 /[pix] E-W offset from sun center
CRVAL2  =              0.00000 /[pix] S-N offset from sun center
```

There's probably a bit of work to be done to parse out the correct observer keywords as well.

**Comment by wtbarnes** [comment]
Would we still want to provide a map source for these files with correct headers though?

**Comment by MSKirk** [comment]
I just chatted with Rachel Hock, the current PI of ISOON about incorporating it into the exiting map environment, and she said "The short answer it is probably not" worth the effort. She is "unlikely to ever have the time or resources to re-do the ISOON processing pipeline" to make it available as a regular source of data. But would like to see "more generic tools for using full-disk ground-based solar images."

**Comment by MSKirk** [comment]
I am not quite sure what generic tools are needed for ground-based solar images, but it looks like anything ISOON specific is not worthwhile.
