### ISSUE TITLE
`GenericMap.draw_contour()` does not make use of the `plot_settings` dictionary

### ISSUE THREAD

**Issue by elastufka** [sunpy/sunpy#6382]
Edit by @ayshih: The issue is that `GenericMap.draw_contour()` does not make use of the `plot_settings` dictionary.

----

### Describe the bug

Including matplotlib.contour kwargs in CompositeMap plot settings don't affect the plot shown using either .peek() or .plot()

The source code indicates that these kwargs should be passed to matplotlib.contour() from GenericMap.draw_contour() so I don't know why this is happening

### To Reproduce

```python
import sunpy

comp_map=sunpy.map.Map(map1, map2,composite=True)
levels = [70,80,90] #contour levels in percent
comp_map.set_levels(index=1, levels=levels, percent=True)

# get plot settings
settings1 = comp_map.get_plot_settings(1)
# for example: {'cmap': 'gray', 'norm': <matplotlib.colors.Normalize at 0x7fd5f0f7dd90>, 'interpolation': 'nearest', 'origin': 'lower'}

#change contour plot settings. Both colors and linewidths are kwargs accepted by matplotlib.contour
color_list = ['#808080' for l in levels]
settings1['colors'] = color_list
settings1['cmap'] = None
settings1['linewidths'] = 2

comp_map.set_plot_settings(1, settings1)
comp_map.plot()
```

### Screenshots

before and after, no change:

![image](https://user-images.githubusercontent.com/11930844/186167037-9662f461-7c8f-4219-acae-959e97a505e6.png)

### System Details

- sunpy version: 3.1.3
- matplotlib version: 3.3.2

### Installation method

conda

**Comment by ayshih** [comment]
Ah.  This isn't actually an issue with `CompositeMap`.  The issue is that `GenericMap.draw_contour()` does not look for appropriate keywords in the `.plot_settings` dictionary when supplying arguments to Matplotlib's `contour()`.  There is no way to "store" settings for contour plotting.  This is presumably due to the inconsistent sets of acceptable keywords for normal plotting and contour plotting...

As an aside, the line `comp_map.set_plot_settings(1, settings1)` in your example does nothing because you have directly modified the non-copied dictionary, so you are simply replacing a dictionary with itself.
