### ISSUE TITLE
Add coronagraph composite-type plot to gallery (e.g. AIA, LASCO C2, C2

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunpy#6420]
### Describe the feature

Add an example to the gallery to show how to plot AIA, LASCO coronagraphs on same figure

**Comment by hayesla** [comment]
also #5471 to add some sample data  and #3098 to mask out coronagraph

**Comment by mwhv2** [comment]
I'd like to start working on this. I am currently creating some composite map replacement tutorials for #6375, and this seems like a natural addition to it.

**Comment by mwhv2** [comment]
Is the following [database](https://lasco-www.nrl.navy.mil/lz/), as suggested in #5471, the best source of level 1 LASCO C2 data for the purpose of adding to the sunpy sample data? As I understand it, LASCO data obtained with Fido is not processed and appears very different than what, for example, Helioviewer shows for a given date/time.

**Comment by dstansby** [comment]
The LASCO website (which seems very out of date in places, but I guess is still the "official" source of information about the data) says the L1 files are calibrated, so I guess it's better to add one of them. On the other hand it looks like no L1 files have been uploaded since 2019, but there are L0.5 files going up to 2022? Since the L0.5 files seem more widely available (including through Fido), if they look okay when plotted then I'd say that's the best option.

I am not a lasco expert or even end user though, so others may know much better than me... (or even know who to contact on the instrument team?)

**Comment by ayshih** [comment]
The "problem" is that the standard LASCO data products do not subtract out the steady background of the corona.  Without that additional processing step, it is rather difficult to see features such as CMEs.  That's why no one ever plots unprocessed LASCO images.
