### ISSUE TITLE
HGS Ticklabels overlap with plot title in "Cropping a Map" example

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/sunpy#6467]
In [the example on cropping a map](https://docs.sunpy.org/en/stable/generated/gallery/map/submaps_and_cropping.html#sphx-glr-generated-gallery-map-submaps-and-cropping-py), we show an HGS grid overlay on a cropped map (see below). However, the tick labels for the HGS grid on the top overlap with the plot title. 

Interestingly, @ayshih says that similar overlaps with HGS axislabels and ticklables  *do not* happen with the following combination of packages:
- sunpy 3.1.8
- astropy 4.3.1
- matplotlib 3.2.2

Whether this is a regression or not is not clear.

![image](https://user-images.githubusercontent.com/8676141/195428910-84d8f83a-d2b1-44af-a884-231c986ae403.png)

**Comment by ayshih** [comment]
Well, the overlap is different with the versions that @wtbarnes listed (which are the versions that are installable on Google Colab), rather than entirely eliminated:
![download (7)](https://user-images.githubusercontent.com/991759/195433726-a1e2cc68-67e8-469d-99f0-006f51b6b750.png)
It seems that one of the packages used to shift the title to make some (but not necessarily enough) room for labels, while the latest packages aren't trying at all.

**Comment by ayshih** [comment]
Looking at the above images again, it looks like the image I posted has the title properly padded for the tick labels, but not for the axis label.  That's in contrast to the image @wtbarnes posted where the title isn't properly padded for either.

**Comment by dstansby** [comment]
Upstream issue reported at https://github.com/astropy/astropy/issues/14047
