### ISSUE TITLE
Parallelise code to update cdaweb datasets

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6519]
### Describe the feature

I'm currently running the code that scrapes CDAWeb for currently supported datasets. The code can be found here: https://github.com/sunpy/sunpy/blob/8c0b9054dc25918ee5b6286a93edbbca09cde903/sunpy/net/cdaweb/helpers.py#L118

The code only fires off one request at a time, waiting for it to come back before putting in the next request. This means it takes a long time (>~5 mins) to scrape all the datasets. I think it *should* be possible to send multiple requests at once to speed this up.

**Comment by lzivadinovic** [comment]
I would like to take a look at this.

**Comment by exitflynn** [comment]
I should be able to do this but it'd involve shifting from using the `requests` module to `aiohttp` for making the requests. Would that be okay? 
[`aiohttp`'s exactly for this purpose](https://docs.aiohttp.org/en/stable/http_request_lifecycle.html#aiohttp-request-lifecycle) and is also how requests are handled in parfive (which is where i first discovered it) so it's already a dependency.

**Comment by nabobalis** [comment]
There was an attempt here: https://github.com/sunpy/sunpy/pull/6601

Unclear what the outcome was as I've not been tracking it.

I think we would need to see an implementation that looked like with aiohttp.

**Comment by exitflynn** [comment]
I remember going through that attempt and it looks like the approach they were going with was :-1:'ed because progress (the name of the databases being upgraded) could no longer be printed as it happened. They had another approach in mind which involved using threads and gnu parallel (which is a Linux-only thing?) but there hasn't been any implementation for that in a while. 

However I believe doing things asynchronously using aiohttp would be a *much* more elegant and suitable approach. Here's a PR I came up with to show how the implementation would look like.

**Comment by exitflynn** [comment]
i wonder if we can use Parfive here to download the data?

**Comment by dstansby** [comment]
Fixed by https://github.com/sunpy/sunpy/pull/6601
