### ISSUE TITLE
Put Attr{Or, And} in sunpy.net.attrs namespace

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunpy#6575]
### Describe the feature

From https://github.com/sunpy/sunpy/pull/6501#discussion_r1005489161:

> If we are going to start documenting this should we not pull AttrOr and AttrAnd into the a. namespace?

**Comment by ryuusama09** [comment]
Hey @dstansby , I woud Like to work on this issue !

**Comment by ryuusama09** [comment]
Hey @dstansby  , so according to this feature request, We just have to add the AttrOr and AttrAnd into attr namespace , am i correct ?

**Comment by nabobalis** [comment]
Hi @ryuusama09, yes that should be enough.

**Comment by ryuusama09** [comment]
@nabobalis , sorry to ask again , but where are these utilities orginally situated and how exactly do you want me to shift them ?. Can you explain in detail. 
Thank you

**Comment by nabobalis** [comment]
> @nabobalis , sorry to ask again , but where are these utilities orginally situated and how exactly do you want me to shift them ?. Can you explain in detail. Thank you

So the main namespace that hosts the main net attributes (attrs for short) live in https://github.com/sunpy/sunpy/blob/main/sunpy/net/attrs.py. This is what we use in examples and tell users to import.

What the issue is, we need to add two new names to this file: AttrOr and AttrAnd. These exist in this file: https://github.com/sunpy/sunpy/blob/main/sunpy/net/attr.py

So the aim would be to import AttrOr and AttrAnd in `attrs.py` and add those two names to the `__all__` list at the bottom.

**Comment by ryuusama09** [comment]
sorry for the late reply , this really helps . Thank you !
