### ISSUE TITLE
Vector orthogonality not maintained when converting from ECI to GSE coordinates

### ISSUE THREAD

**Issue by Evidlo** [sunpy/sunpy#6719]
### Describe the bug

I'm using sunpy to convert from ECI (Earth centered inertial) to GSE (Geocentric solar ecliptic) coordinates.  I'm converting a set of three orthogonal unit vectors and I expect the orthogonality and magnitude to be preserved after conversion (ECI to GSE should just be a rotation, right?).

For most dates, the conversion seems to work just fine, but for some very specific dates it seems that the resultant vectors are no longer orthogonal.  I've included some code that does the conversion and plots the result and compared against a conversion done by the [spacepy](https://spacepy.github.io) project which does the conversion correctly.

### To Reproduce
``` python
#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
from astropy.time import Time, TimeDelta

import astropy.coordinates as acoord
import sunpy.coordinates as scoord

from spacepy import coordinates as spcoord
from spacepy.time import Ticktock

def arrows3d(ends, starts=None, ax=None, label=None, **kwargs):
    """3D plot of multiple arrows

    Args:
        ends (ndarray): (N, 3) size array of arrow end coordinates
        starts (ndarray): (N, 3) size array of arrow start coordinates.
            Assume start position of (0, 0, 0) if not given
        ax (Axes3DSubplot): existing axes to add to
        label (str): legend label to apply to this group of arrows
        kwargs (dict): additional arrow properties
    """
    from matplotlib.patches import FancyArrowPatch
    from mpl_toolkits.mplot3d import proj3d

    if starts is None:
        starts = np.zeros_like(ends)

    assert starts.shape == ends.shape, "`starts` and `ends` shape must match"
    assert len(ends.shape) == 2 and ends.shape[1] == 3, \
        "`starts` and `ends` must be shape (N, 3)"

    class Arrow3D(FancyArrowPatch):
        def __init__(self, xs, ys, zs, *args, **kwargs):
            super().__init__((0,0), (0,0), *args, **kwargs)
            self._verts3d = xs, ys, zs

        def do_3d_projection(self, renderer=None):
            xs3d, ys3d, zs3d = self._verts3d
            xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
            self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))

            return np.min(zs)

    # create new axes if none given
    if ax is None:
        ax = plt.figure().add_subplot(111, projection='3d')

    arrow_prop_dict = dict(mutation_scale=20, arrowstyle='-|>', color='k', shrinkA=0, shrinkB=0)
    arrow_prop_dict.update(kwargs)
    for ind, (s, e) in enumerate(np.stack((starts, ends), axis=1)):
        a = Arrow3D(
            [s[0], e[0]], [s[1], e[1]], [s[2], e[2]],
            # only give label to first arrow
            label=label if ind == 0 else None,
            **arrow_prop_dict
        )
        ax.add_artist(a)

    # store starts/ends on the axes for setting the limits
    ax.points = np.vstack((starts, ends, getattr(ax, 'points', np.empty((0, 3)))))
    ax.set_xlim3d(ax.points[:, 0].min(),ax.points[:, 0].max())
    ax.set_ylim3d(ax.points[:, 1].min(),ax.points[:, 1].max())
    ax.set_zlim3d(ax.points[:, 2].min(),ax.points[:, 2].max())

    return ax

def eci_to_gse_sunpy(eci, time):
    """Convert ECI to GSE using sunpy"""
    xyz_sky = acoord.SkyCoord(
        x=eci[0], y=eci[1], z=eci[2],
        frame='gcrs', unit='km', representation_type='cartesian', obstime=time
    )

    #Transform to GSE
    GSE = scoord.GeocentricSolarEcliptic(obstime=time)
    xyz_sky = xyz_sky.transform_to(GSE)
    xyz_sky.representation_type = 'cartesian'

    #Extract values
    return np.stack((xyz_sky.x.value, xyz_sky.y.value, xyz_sky.z.value), axis=0)

def eci_to_gse_spacepy(eci, time):
    """Convert ECI to GSE using spacepy"""

    cvals = spcoord.Coords(eci, 'ECITOD', 'car')
    cvals.ticks = Ticktock([time.to_datetime()] * 3)
    gse = cvals.convert('GSE', 'car')
    return np.stack((gse.x, gse.y, gse.z), axis=0)

# test input coordinates in ECI
eci = np.array((
    (1, 0, 0),
    (0, 1, 0),
    (0, 0, 1)
))

time = Time('2025-06-01')

# convert test coordinates to GSE
gse_sunpy = eci_to_gse_sunpy(eci, time)
gse_spacepy = eci_to_gse_spacepy(eci, time)

# --- plotting ---
plt.close()
ax = arrows3d(eci, color='r', label='ECI')
arrows3d(gse_sunpy, ax=ax, color='g', label='GSE (sunpy)')
# scale spacepy result so vectors don't lie on top of each other
arrows3d(gse_spacepy * 1.1, ax=ax, color='b', label='GSE (spacepy)')
ax.set_aspect('equal')
plt.title('Coordinates')
plt.legend()
plt.tight_layout()

plt.show()
```

### Screenshots

![fig](https://user-images.githubusercontent.com/5455841/213585259-166c5d37-d309-4762-b204-3f7010b18e13.png)

### System Details

- sunpy: 4.0.4
- astropy: 5.1
- python: 3.10.5

### Installation method

pip

**Comment by Evidlo** [comment]
I also plotted the determinant of the resultant 3-by-3 matrix vs time.  If the conversion was just a rotation, we would expect the determinant of the result to always be 1.

``` python
# test input coordinates in ECI
eci = np.array((
    (1, 0, 0),
    (0, 1, 0),
    (0, 0, 1)
))
center_time = Time('2025-06-01')

# --- plotting 2D ---

gse_sunpy = []
gse_spacepy = []
day_offset = np.linspace(-50, 50, 1000)
for d in day_offset:
    time = center_time + TimeDelta(d)
    gse_sunpy.append(np.linalg.det(eci_to_gse_sunpy(eci, time)))
    gse_spacepy.append(np.linalg.det(eci_to_gse_spacepy(eci, time)))

plt.plot(day_offset, gse_sunpy, label='GSE (sunpy)')
plt.plot(day_offset, gse_spacepy, label='GSE (spacepy)')
plt.xlabel('Day offset from ' + str(center_time))
plt.ylabel('Determinant')
plt.legend()
```

![fig2](https://user-images.githubusercontent.com/5455841/213586685-2a5b2bb5-d505-4572-9038-326c116491ca.png)

**Comment by ayshih** [comment]
Thanks for the report!  This is going to be a long response, and feel free to ask follow-up questions.

### Transforming a vector too close to an origin when there's an origin shift

For the sunpy coordinate transformation, you are transforming from Astropy's `GCRS` to sunpy's `GeocentricSolarEcliptic`.  However, as you can see from our transformation graph (https://docs.sunpy.org/en/stable/code_ref/coordinates/index.html#module-sunpy.coordinates), the resulting transformation path is `GCRS`->`ICRS`->`HeliocentricMeanEcliptic`->`HeliocentricEarthEcliptic`->`GeocentricSolarEcliptic`, and the critical aspect is that there are massive shifts in origin on the order of an AU.

For vectors that are far away from any origin, this isn't necessarily an issue, but you are instantiating a coordinate that is merely one kilometer from Earth center.  Thus, you get slammed with numerical-precision problems by shifting 1 AU away, applying a slight rotation, and then eventually shifting 1 AU back.

For this transformation path, the workaround to get much better agreement is to use a much larger unit than a kilometer, whether that's Earth radii like SpacePy or simply a megameter.

### Non-equivalent frame definitions

Coordinate frames are confusing, no question about that.  However, you can't actually use SpacePy's `ECITOD` because there's no frame of equivalent definition in sunpy/Astropy.  You should actually use sunpy's `GeocentricEarthEquatorial`, which corresponds to SpacePy's `ECI2000` when `equinox=J2000.0` (the default value) and corresponds to SpacePy's `ECIMOD` when `equinox` is set to the observation time.  (There's still an origin shift in the transformation path between `GeocentricEarthEquatorial` and `GeocentricSolarEcliptic`, but we could fix that by adding a direct transformation.)

That is, these are the two appropriate comparisons:

- sunpy's `GeocentricEarthEquatorial(..., equinox=J2000.0)` -> `GeocentricSolarEcliptic`, versus SpacePy's `ECI2000` -> `GSE`
- sunpy's `GeocentricEarthEquatorial(..., equinox=time)` -> `GeocentricSolarEcliptic`, versus SpacePy's `ECIMOD` -> `GSE`

Astropy's `GCRS` is very similar to sunpy's `GeocentricEarthEquatorial`, but you shouldn't use it because (1) it is intended for telescope observations so includes the effect of stellar aberration and (2) does not include the frame bias between ICRF and dynamical J2000.0.  Astropy's `PrecessedGeocentric` is better to use than `GCRS` because it takes care of frame bias for J2000.0, and it can be precessed to MOD, but you shouldn't use it either because it still includes stellar aberration.

### Not plotting valid vectors

Your plot of the vectors looks weird because the output of your two functions has the vectors as columns, but then you are plotting the rows as if they are the vectors.  The large green vector that's pointing off in a weird direction is actually the three Z components of each of the three vectors interpreted as a new vector.

There's an additional bug where you need to transpose `eci` before using it the way you do in `eci_to_gse_sunpy()` to be consistent with how it is used in `eci_to_gse_spacepy()`, but it doesn't literally affect your example code because `eci` is diagonal.

### Miscellaneous

- You call the property `.value` on the components of the `GeocentricSolarEcliptic` coordinate.  You shouldn't do that on Astropy `Quantity` instances unless you are certain what the units are ahead of time.  For example, if we changed the default unit for `GeocentricSolarEcliptic` in sunpy, suddenly your output would change.  It's better to use `.to_value()` to make sure that the value is in the unit that you want it to be in.
- SpacePy's `Ticktock` can accept Astropy `Time` input, so no need to go through `datetime`, which can only cause issues,

**Comment by Evidlo** [comment]
@ayshih Thanks for the detailed response.  The suggested changes seem to have resolved the issues I was having.  The code is included below for posterity.

> SpacePy's Ticktock can accept Astropy Time input, so no need to go through datetime, which can only cause issues,

This may be a SpacePy bug and is irrelevant to this issue, but `Ticktock` throws an error when provided with a list of Astropy Time objects.

``` python
>>> Ticktock(time)
Out[24]: Ticktock( ['2025-06-02 00:00:00.000'], dtype=APT)

>>> Ticktock([time, time, time])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[25], line 1
----> 1 Ticktock([time, time, time])

File ~/miniconda3/lib/python3.9/site-packages/spacepy/time.py:389, in Ticktock.__init__(self, data, dtype, isoformat)
    387     dtype = 'APT'
    388     # Recover original input (not dmarray), add axis if scalar
--> 389     self.data = astropy.time.Time([data]) if data.shape == ()\
    390                 else data
    391 elif self.data[0] > 1e13:
    392     dtype = 'CDF'

AttributeError: 'list' object has no attribute 'shape'
```

```
#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
from astropy.time import Time, TimeDelta

import astropy.coordinates as acoord
import sunpy.coordinates as scoord

from spacepy import coordinates as spcoord
from spacepy.time import Ticktock

def arrows3d(ends, starts=None, ax=None, label=None, **kwargs):
    """3D plot of multiple arrows

    Args:
        ends (ndarray): (N, 3) size array of arrow end coordinates
        starts (ndarray): (N, 3) size array of arrow start coordinates.
            Assume start position of (0, 0, 0) if not given
        ax (Axes3DSubplot): existing axes to add to
        label (str): legend label to apply to this group of arrows
        kwargs (dict): additional arrow properties
    """
    from matplotlib.patches import FancyArrowPatch
    from mpl_toolkits.mplot3d import proj3d

    if starts is None:
        starts = np.zeros_like(ends)

    assert starts.shape == ends.shape, "`starts` and `ends` shape must match"
    assert len(ends.shape) == 2 and ends.shape[1] == 3, \
        "`starts` and `ends` must be shape (N, 3)"

    class Arrow3D(FancyArrowPatch):
        def __init__(self, xs, ys, zs, *args, **kwargs):
            super().__init__((0,0), (0,0), *args, **kwargs)
            self._verts3d = xs, ys, zs

        def do_3d_projection(self, renderer=None):
            xs3d, ys3d, zs3d = self._verts3d
            xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
            self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))

            return np.min(zs)

    # create new axes if none given
    if ax is None:
        ax = plt.figure().add_subplot(111, projection='3d')

    arrow_prop_dict = dict(mutation_scale=20, arrowstyle='-|>', color='k', shrinkA=0, shrinkB=0)
    arrow_prop_dict.update(kwargs)
    for ind, (s, e) in enumerate(np.stack((starts, ends), axis=1)):
        a = Arrow3D(
            [s[0], e[0]], [s[1], e[1]], [s[2], e[2]],
            # only give label to first arrow
            label=label if ind == 0 else None,
            **arrow_prop_dict
        )
        ax.add_artist(a)

    # store starts/ends on the axes for setting the limits
    ax.points = np.vstack((starts, ends, getattr(ax, 'points', np.empty((0, 3)))))
    ax.set_xlim3d(ax.points[:, 0].min(),ax.points[:, 0].max())
    ax.set_ylim3d(ax.points[:, 1].min(),ax.points[:, 1].max())
    ax.set_zlim3d(ax.points[:, 2].min(),ax.points[:, 2].max())

    return ax

def eci_to_gse_sunpy(eci, time):
    """Convert ECI to GSE using sunpy"""
    eci = eci * 1e6
    xyz_sky = acoord.SkyCoord(
        x=eci[0], y=eci[1], z=eci[2],
        frame=scoord.GeocentricEarthEquatorial,
        # frame='gcrs',
        unit='km', representation_type='cartesian', obstime=time
    )

    #Transform to GSE
    GSE = scoord.GeocentricSolarEcliptic(obstime=time)
    xyz_sky = xyz_sky.transform_to(GSE)
    xyz_sky.representation_type = 'cartesian'

    #Extract values
    return np.stack(
        (xyz_sky.x.to_value('km'), xyz_sky.y.to_value('km'), xyz_sky.z.to_value('km')),
        axis=0
    ) / 1e6

def eci_to_gse_spacepy(eci, time):
    """Convert ECI to GSE using spacepy"""

    cvals = spcoord.Coords(eci, 'ECI2000', 'car')
    cvals.ticks = Ticktock([time.to_datetime()] * 3)
    return cvals.convert('GSE', 'car').data.T

# test input coordinates in ECI
eci = np.array((
    (1, 0, 0),
    (0, 1, 0),
    (0, 0, 1)
))
center_time = Time('2025-06-01')

# --- plotting 2D ---

gse_sunpy = []
gse_spacepy = []
day_offset = np.linspace(-1, 1, 300)
for d in day_offset:
    time = center_time + TimeDelta(d)
    gse_sunpy.append(np.linalg.det(eci_to_gse_sunpy(eci.T, time)))
    gse_spacepy.append(np.linalg.det(eci_to_gse_spacepy(eci.T, time)))

plt.plot(day_offset, gse_sunpy, label='GSE (sunpy)')
plt.plot(day_offset, gse_spacepy, label='GSE (spacepy)')
plt.xlabel('Day offset from ' + str(center_time))
plt.ylabel('Determinant')
plt.ylim([-1.1, 1.1])
plt.legend()

# --- plotting 3D ---

# # convert test coordinates to GSE
# gse_sunpy = eci_to_gse_sunpy(eci.T, center_time).T
# gse_spacepy = eci_to_gse_spacepy(eci.T, center_time).T
# plt.close()
# ax = arrows3d(eci, color='r', label='ECI')
# arrows3d(gse_sunpy, ax=ax, color='g', label='GSE (sunpy)')
# # scale spacepy result so vectors don't lie on top of each other
# arrows3d(gse_spacepy * 1.1, ax=ax, color='b', label='GSE (spacepy)')
# ax.set_aspect('equal')
# plt.title('Coordinates')
# plt.legend()
# plt.tight_layout()

plt.show()
```

**Comment by ayshih** [comment]
> This may be a SpacePy bug and is irrelevant to this issue, but `Ticktock` throws an error when provided with a list of Astropy Time objects.

@Evidlo: It works if you convert the list to a single Astropy `Time` instance.  To fix your example code:
```python
>>> Ticktock(Time([time, time, time]))
Ticktock( ['2025-06-01 00:00:00.000' '2025-06-01 00:00:00.000'
 '2025-06-01 00:00:00.000'], dtype=APT)
```
