### ISSUE TITLE
Importing `sunpy.map` or other submodule breaks `WCS.pixel_to_world()` API

### ISSUE THREAD

**Issue by ebuchlin** [sunpy/sunpy#6790]
### Describe the bug

The output type of `WCS.pixel_to_world()` changes after `sunpy.map` or `sunpy.visualization.colormaps` (but not `sunpy` alone) are imported.

I understand that sunpy must do something like "registering" solar coordinate frames to astropy.wcs (like it does for matplotlib color maps), but why should the output type change? This can be confusing to users who do not systematically import such submodules.

### To Reproduce

```python
from astropy.wcs import WCS
from astropy.io import fits

# this is just a path, it does not import anything else from sunpy
from sunpy.data.sample import AIA_171_IMAGE

with fits.open(AIA_171_IMAGE) as hdul:
    wcs = WCS(hdul[1].header)
print(wcs)
# Output:
# WCS Keywords
#
# Number of WCS axes: 2
# CTYPE : 'HPLN-TAN'  'HPLT-TAN'
# CRVAL : 0.00089530541880571  0.00038493926472938695
# CRPIX : 512.5  512.5
# NAXIS : 1024  1024
print(wcs.pixel_to_world(512, 512))
# Output:
# [<Quantity 0.00122983 deg>, <Quantity 0.00071785 deg>]

import sunpy.map
print(wcs)
# Output:
# WCS Keywords
#
# Number of WCS axes: 2
# CTYPE : 'HPLN-TAN'  'HPLT-TAN'
# CRVAL : 0.00089530541880571  0.00038493926472938695
# CRPIX : 512.5  512.5
# NAXIS : 1024  1024
print(wcs.pixel_to_world(512, 512))
# Output:
# <SkyCoord (Helioprojective: obstime=2011-06-07T06:33:02.770, rsun=696000.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2011-06-07T06:33:02.770, rsun=696000.0 km): (lon, lat, radius) in (deg, deg, m)
#     (0.07778097, 0.048591, 1.51846026e+11)>): (Tx, Ty) in arcsec
#     (4.42740299, 2.58426282)>
```

### System Details

```
==============================
sunpy Installation Information
==============================

General
#######
OS: Ubuntu (22.10, Linux 5.19.0-31-generic)
Arch: 64bit, (x86_64)
sunpy: 4.1.0
Installation path: /home/eric/.local/lib/python3.10/site-packages/sunpy-4.1.0.dist-info

Required Dependencies
#####################
astropy: 5.1.1
numpy: 1.23.4
packaging: 21.3
parfive: 2.0.2

Optional Dependencies
#####################
asdf: 2.14.3
asdf-astropy: 0.2.2
beautifulsoup4: 4.11.1
cdflib: 0.4.7
dask: 2022.2.0+dfsg
drms: 0.6.2
glymur: 0.11.6.post1
h5netcdf: 1.0.2
h5py: Missing h5py>=3.1.0; extra == "timeseries"
lxml: 4.9.1
matplotlib: 3.6.2
mpl-animators: 1.1.0
pandas: 1.4.4
python-dateutil: 2.8.1
reproject: 0.9
scikit-image: 0.19.3
scipy: 1.9.3
sqlalchemy: 1.4.40
tqdm: 4.64.1
zeep: 4.1.0
```

### Installation method

pip

**Comment by Cadair** [comment]
hey @ebuchlin

This is a little confusing, but is fundamentally an issue of where the scope of astropy ends and the scope of sunpy begins.

The two lines of code which need to be executed are here: https://github.com/sunpy/sunpy/blob/main/sunpy/coordinates/wcs_utils.py#L262-L263 so what you need to import to get the sunpy behaviour is `sunpy.coordinates`.

Astropy has the wcs subpackage, which by itself has some support for solar frames, but what Astropy doesn't have is the coordinate frames in `sunpy.coordinates` or the mapping of those frames to WCS keys (`CTYPE`). SunPy is the logical place for those frames to exist, and the mappings as well (because they are meaningless without the frames). So we end up in a situation where having imported `sunpy.coordinates` makes the `astropy.coordinates` frame graph and `astropy.wcs.WCS` class aware of more frames, so they are returned to the user.

If, for some explicit reason, you wanted a way to avoid the behaviour changing depending on if sunpy has been imported or not, you could use `pixel_to_world_values` as that wouldn't change as it would just return the numbers.

**Comment by ayshih** [comment]
To help clarify, the variation in the API is due to a design choice in astropy.  `WCS.pixel_to_world()` returns a `SkyCoord` instance if it can find a valid mapping to a coordinate frame, otherwise it will return a pair of `Quantity` instances.  It's only upon importing `sunpy.coordinates` (which is triggered by importing `sunpy.map`) that Astropy is provided a mapping to our `Helioprojective` frame class.  Changing this behavior would require a change in astropy, not sunpy.

**Comment by ebuchlin** [comment]
OK, thanks for the explanation!

**Comment by ebuchlin** [comment]
For users who absolutely want to keep the original behavior and not use `pixel_to_world_values`, it is possible to "unregister" the mapping with
```python
from astropy.wcs.utils import WCS_FRAME_MAPPINGS, FRAME_WCS_MAPPINGS
for mapping in [WCS_FRAME_MAPPINGS, FRAME_WCS_MAPPINGS]:
     if mapping[-1][0].__module__ == 'sunpy.coordinates.wcs_utils':
         mapping.pop()
```
or something like that, after importing the SunPy submodules. This is probably not to be used for any serious code, and would break other SunPy coordinates functionalities, but it can be a quick bypass of the issue in some cases.
