### ISSUE TITLE
Cropping a Map example shows an unexpected out message.

### ISSUE THREAD

**Issue by davnish** [sunpy/sunpy#6818]
While I was browsing through the Sunpy Example Gallery, I Came across this example [Cropping A Map](https://docs.sunpy.org/en/stable/generated/gallery/map/submaps_and_cropping.html#sphx-glr-generated-gallery-map-submaps-and-cropping-py) which shows an unexpected out message.

### Screenshots

<img width="806" alt="Screenshot 2023-03-03 at 12 36 25 PM" src="https://user-images.githubusercontent.com/32027279/222654213-2e616931-803a-4aa7-b347-5440bf0197af.png">

**Comment by nabobalis** [comment]
As far as I am aware, that is an expected output when using that file as the original file is missing relevant metadata. People who are more familiar with that data source will need to chime in. 

I had thought we had suppressed them on the stable version of the documentation but clearly not.

**Comment by ayshih** [comment]
> I had thought we had suppressed them on the stable version of the documentation but clearly not.

We shouldn't suppress such messages.  Especially in a tutorial, we must faithfully render exactly what a user will see when they follow along with the example, otherwise they may think that their local setup is broken.  The deficiency in the example is failing to acknowledge those messages in the accompanying text and provide assurance to the user.

There are better steps we could take, such as adding some code after map instantiation to modify the metadata. or simply picking a different example file.
