### ISSUE TITLE
Make Map preserve the formatting of the HISTORY metadata

### ISSUE THREAD

**Issue by jslavin** [sunpy/sunpy#6908]
### Describe the feature

After reading in a fits file using Map, it seems that all the \n's are thrown away for the information in the HISTORY. That makes reading that metadata much harder. It'd be nice if SunPy could treat the HISTORY metadata the way astropy.io.fits does, which preserves its format. As an example, here's part of a XRT image's metadata as viewed with fitsheader:
```
HISTORY LEVEL1_PREP v2015.May.19 NOTE: No spot correction done for this image;  
HISTORY (cont'd) XRT_SPOTCOR information applies to associated jpeg files only  
HISTORY XRT_SPOTCOR v2014-Apr-14: (23-May-2015 00:52:36) All spots and dust     
HISTORY (cont'd) corrected with thin plate splines. Spot mastermap version =    
HISTORY (cont'd) v20080206. Threshold = 0.500000
```

Here's what that part looks like after being read in by Map and then printed via print(m.fits_header)
```
HISTORY gin(cont'd) file: XRT20120605_215839.9.fitsLEVEL1_PREP v2015.May.19 NOTE
HISTORY : No spot correction done for this image;(cont'd) XRT_SPOTCOR informatio
HISTORY n applies to associated jpeg files onlyXRT_SPOTCOR v2014-Apr-14: (23-May
HISTORY -2015 00:52:36) All spots and dust(cont'd) corrected with thin plate spl
HISTORY ines. Spot mastermap version =(cont'd) v20080206. Threshold = 0.500000XR
```
### Proposed solution

I'm not sure where or how SunPy joins the lines in the HISTORY metadata, but it seems that the line breaks are somehow removed at that point. So, it may be as easy as not removing the line breaks. I looked through the code a bit and didn't see any place where HISTORY metadata is treated differently than any other data in the map code. In astropy there is a separate type of header keyword called a commentary_keyword. Maybe SunPy needs something like that.

**Comment by wtbarnes** [comment]
The relevant code here is actually with the way `sunpy.io` parses the HISTORY key,

https://github.com/sunpy/sunpy/blob/61047b4b8a1d47e29d3417e419197931b89e1b4a/sunpy/io/_fits.py#L157

When parsing the metadata to pass it to `Map`, each key must be unique because the metadata is exposed a dictionary which is why all of the `HISTORY` keys are joined. That being said, I'm not sure there's any reason we couldn't just join each `HISTORY` entry with a newline character so that it would at least print more nicely to the screen. 

This is also relevant to #931 (opened almost exactly 9 years ago!) and probably something we should consider as we are rethinking the sunpy metadata model.

**Comment by wtbarnes** [comment]
> So a simple fix to the formatting problem is to just remove the .strip() from that line.

The problem is `"".join()`. All the history cards are being joined together with no characters in between. Joining all the characters with newlines in between should fix this issue, e.g. `"\n".join()`. The `strip()` call is just stripping the leading and trailing white space. 

> I wonder though why SunPy needs define its own metadata format. astropy is already a requirement. Why not just use their Header class to store the metadata?

This is a fair question. One advantage of `MetaDict` is that it is case-insensitive (unlike `astropy.io.fits.Header`).  Additionally, the `MetaDict` approach is a quite old part of `sunpy`. See #49. It is possible that `astropy.io.fits.Header` was not nearly as mature when `MetaDict`/`MapHeader` was developed. Also, as outlined in that very old PR, by not tying the metadata object directly to the FITS header, we have the advantage of a metadata model that is independent of file format/the FITS standard. Of course, in practice, Maps have been used almost exclusively with FITS data (with the exception of JPEG-2000 images).

Moving forward, this independence from FITS will only become more important as non-FITS WCS models (e.g. gwcs) become more prevalent so I don't think it makes sense currently to replace our metadata model with `astropy.io.fits.Header`. We do not yet have a clear path forward on how to proceed when it comes to a new metadata model, but the a draft of the current thinking is outlined in sunpy/sunpy-SEP#61. Input is very much welcome!

**Comment by jslavin** [comment]
Okay I can see the desire to be independent of the FITS standard. Still though the ability to easily add information to the HISTORY metadata key as can be done with the astropy Header class would be good. The idea that there are keys such as COMMENT and HISTORY that are different from the others, in the sense that they are easy to add metadata to, would be good to include in whatever form the metadata model takes.

**Comment by wtbarnes** [comment]
> Still though the ability to easily add information to the HISTORY metadata key as can be done with the astropy Header class would be good. 

I agree. It would be good to establish some standard API for doing this.

I think one of the blockers for this is determining how "prep" methods should serialize their operations to a `HISTORY` key. As far as I know, every mission does this slightly differently. For example, what should a method like `rotate` or `resample` add to `HISTORY`? The discussion on this `aiapy` issue is also relevant: https://gitlab.com/LMSAL_HUB/aia_hub/aiapy/-/issues/56.

It is clumsy, but you can just add text to the `history` key and save that to the file.

```python
m.meta['history'] += '\nAnother entry to the history'
```
