### ISSUE TITLE
Customize reference pixel longitude in `sunpy.map.header_helper.make_heliographic_header`

### ISSUE THREAD

**Issue by STBadman** [sunpy/sunpy#7023]
### Describe the feature

`sunpy.map.header_helper.make_heliographic_header` has a hardcoded reference pixel coordinate which assumes the map center is at 0 degrees. This makes sense for the stonyhurst reference frame but when creating maps in the carrington frame, 0 is often at the left hand edge of the map or at an arbitrary roll. 

It is very straightforward to simply introduce a keyword to the function that allows a user to modify the reference pixel longitude from 0. 

### Proposed solution

Add a keyword `map_center_longitude` with an `astropy.units.quantity_input` decorator to `sunpy.map.header_helper.make_heliographic_header`  and pass the keyword to the creation of the reference pixel coordinate inside the function.

See :  https://github.com/sunpy/sunpy/compare/main...STBadman:sunpy:heliographic_headers and similar to [`pfsspy.utils.carr_cea_wcs_header` ](https://github.com/dstansby/pfsspy/blob/main/pfsspy/utils.py)

Please let me know if this seems reasonable and I can request a PR from my fork. Thank you!

**Comment by ayshih** [comment]
I agree that it's less common for Carrington maps to have zero longitude at map center.  I'd be in favor of changing the stock behavior of `make_heliographic_header()` so that Carrington maps go from 0 to 360 degrees in longitude, but there are probably people that would dislike such a change.

I'm not keen on adding a keyword option to `make_heliographic_header()`.  (Others are welcome to voice contrary opinions!)  That convenience function is a stripped-down version of `make_fitswcs_header()`, so adding a keyword option is fighting against the stripping down.  If someone needs an unusual WCS, I'm inclined to just point them to `make_fitswcs_header()`.

Note that it is straightforward to work around the current behavior by simply modifying `CRVAL1`/`CRPIX1` in the returned header.

**Comment by schonfsj** [comment]
I am strongly in support of @STBadman's original suggestion that this should be a user-defined keyword (although I'm not opposed to also changing the default behavior).

I just spent the better part of a day trying to figure this out, although I did eventually discover that modifying `CRVAL1`/`CRPIX1` could achieve the desired result. I found this manual fix quite non-intuitive because I could not simply reassign values in the `sunpy.util.metadata.MetaDict` object returned by `make_heliographic_header()` and instead had to call the `update()` method with a new dictionary (`{'crval1':180}`). Perhaps there is an easier way to manually modify the results from `make_heliographic_header()`, but it was not obvious to me that my attempts to set `header['crval1']=180` were failing to change the value in `header` rather than just not achieving the desired effect in the resulting figures.

**Comment by ayshih** [comment]
I just chatted with @schonfsj about this feature request, and I'm now on board to add a keyword to `make_heliographic_header()`.  @STBadman: do you want to create a PR?

**Comment by STBadman** [comment]
Thanks @ayshih and @schonfsj , that's great news. Yes, happy to submit the PR, I will do so early next week.

**Comment by wtbarnes** [comment]
It looks like this was closed by #7143. If this is not the case, feel free to reopen.
