### ISSUE TITLE
AIA world_to_pixel bug produces Nans

### ISSUE THREAD

**Issue by cdiazbas** [sunpy/sunpy#7085]
### Describe the bug

The world_to_pixel method does not work properly with some AIA images, producing Nans, while for other channels very close in time, it does. The output is wrong and contains Nans. The AIA data has been downloaded using Fido, as usual.

### To Reproduce

import sunpy.map
import astropy.units as u
from astropy.coordinates import SkyCoord

files = [
    '../data/aia_lev1_171a_2020_03_17t00_20_09_35z_image_lev1.fits',
    '../data/aia_lev1_1600a_2020_03_17t00_20_14_13z_image_lev1.fits'
]

m_aia_171 = sunpy.map.Map(files[0])
m_aia_1600 = sunpy.map.Map(files[1])

xlims_world = [500, 1100]*u.arcsec
ylims_world = [-800, 0]*u.arcsec

world_coords = SkyCoord(Tx=xlims_world, Ty=ylims_world, frame=m_aia_171.coordinate_frame)
pixel_coords_171 = m_aia_171.wcs.world_to_pixel(world_coords)
pixel_coords_1600 = m_aia_1600.wcs.world_to_pixel(world_coords)
print(pixel_coords_171)
print(pixel_coords_1600)

### Output

pixel_coords_171 -> (array([2887.46601034, 3888.78297357]), array([ 712.3738331 , 2046.51757479]))
pixel_coords_1600 -> (array([2871.24983965,           nan]), array([733.18207207,          nan]))

### System Details

==============================
sunpy Installation Information
==============================

General
#######
OS: Mac OS 12.6.6
Arch: 64bit, (arm)
sunpy: 5.0.0

Required Dependencies
#####################
astropy: 5.3
numpy: 1.24.2
packaging: 23.1
parfive: 2.0.2

Optional Dependencies
#####################
asdf: 2.15.0
asdf-astropy: 0.4.0
beautifulsoup4: 4.12.2
cdflib: 0.0.0
dask: 2023.6.1
drms: 0.6.4
glymur: 0.12.7
h5netcdf: 1.2.0
h5py: 3.9.0
lxml: 4.9.2
matplotlib: 3.7.1
mpl-animators: 1.1.0
pandas: 2.0.3
python-dateutil: 2.8.2
reproject: 0.11.0
scikit-image: 0.20.0
scipy: 1.11.1
sqlalchemy: 2.0.17
tqdm: 4.65.0
zeep: 4.2.1

### Installation method

conda

**Comment by ayshih** [comment]
You are asking for the pixel locations in your 1600 A map for 2D world coordinates defined in the coordinate frame of your 171 A map.  Formally, that requires converting a 2D world coordinate to a 3D world coordinate (i.e., there needs to be a value for the distance from the observer) so that the coordinate can be transformed from the the coordinate frame of your 171 A map to the coordinate frame of your 1600 A map, which are slightly different because AIA has moved slightly between the observation times.

For a 2D world coordinate that is on the solar disk, the default behavior is to assume that the 3D world coordinate is on the surface of the Sun.  For a 2D world coordinate that is beyond the solar limb, as is the case for your `world_coords[1]`, the default behavior is to simply return NaN as the distance from the observer because there is no "safe" assumption that is broadly applicable.

It's unfortunate that your test case included both on-disk and off-disk coordinates.  If you supplied coordinates that were all off-disk, e.g., `world_to_pixel(world_coords[1])`, you might have seen the following warning message:
> WARNING: SunpyUserWarning: The conversion of these 2D helioprojective coordinates to 3D is all NaNs because off-disk coordinates need an additional assumption to be mapped to calculate distance from the observer. Consider using the context manager `Helioprojective.assume_spherical_screen()`. [sunpy.coordinates.frames]

As that warning message indicates, my recommendation is that you use the context manager [`Helioprojective.assume_spherical_screen()`](https://docs.sunpy.org/en/stable/generated/api/sunpy.coordinates.frames.Helioprojective.html#sunpy.coordinates.frames.Helioprojective.assume_spherical_screen).  Here's how that would work in your example:
```python
>>> from sunpy.coordinates import Helioprojective

>>> with Helioprojective.assume_spherical_screen(m171.observer_coordinate, only_off_disk=True):
...     pixel_coords_171 = m171.wcs.world_to_pixel(world_coords)
...     pixel_coords_193 = m193.wcs.world_to_pixel(world_coords)

>>> print(pixel_coords_171)
(array([719.05779338, 967.96372033]), array([178.47655131, 512.02928467]))

>>> print(pixel_coords_193)
(array([718.07009901, 968.08661663]), array([178.20218883, 510.87132123]))
```

Does that make sense?

**Comment by cdiazbas** [comment]
Dear @ayshih , thank you very much for your feedback and explanation. I reported as a bug because I did not fully understand the behavior. Maybe it would be interesting to extend the warning for cases like this, where at least one of the coordinates is off-disk. Feel free to close this issue.

**Comment by ayshih** [comment]
We emit that warning only if all of the output coordinates are NaNs because we figure that the user probably didn't want all NaNs (although there are situations where that is the desired output).  We don't want to emit a warning when only some of the output coordinates are NaNs because there are enough cases where it's natural to be transforming a combination of on-disk and off-disk coordinates, most notably when reprojecting a map.
