### ISSUE TITLE
Map contour naming convention

### ISSUE THREAD

**Issue by settwi** [sunpy/sunpy#7910]
The naming of `GenericMap.get_contours` came up in a separate thread. I think a better name might be `compute_contours`, as they aren't intrinsic to the map to be "gotten." This is basically just a matter of personal preference, but it might be worth considering a name change.

---
_original comment_

any method starting with `get_` makes me sad. is there a better verb? maybe, `compute_contours` ?

_Originally posted by @settwi in https://github.com/sunpy/sunpy/issues/7420#issuecomment-2524946923_

**Comment by ayshih** [comment]
I prefer `get_contours()` over `compute_contours()`.  The purpose of the method is to "get" a contour, however that is done internally.  The API should not concern itself with whether the contours are (somehow) pre-computed or are computed on the fly.

**Comment by settwi** [comment]
In my mind “get” implies that they ARE in pre-computed, or otherwise pre-associated with the data. so either way the intent is encoded in the name.

i guess given that, “get” is shorter so maybe it’s the way to go. generally any method starting with “get” makes me wonder if a better word could be used. but perhaps there isn't one here

**Comment by settwi** [comment]
A couple of other notes
- The current documentation references `contourpy` and `skimage` algorithms which explicitly _do_ compute the contours
- If a more specific verb is used like `compute` or `find`, then the intent can be clearer to the user that the API does in fact compute them on the fly

**Comment by ayshih** [comment]
> the API does in fact compute them on the fly

To be clear, API is distinct from implementation.  My perspective is that the API – here, the name of the method – should be agnostic about whether contours will be computed.  The documentation of the method is the place to describe the actual implementation.  To take it to an absurd extreme, we certainly would never name the method `compute_contours_using_contourpy()`.

I'm not saying that "get" is a great verb to use, because it certainly can have connotations, but I think "compute" is a worse choice.  I could probably get on board with "find".

**Comment by naxatra2** [comment]
Also, most functions in Sunpy have naming conventions similar to `get_contours`. In general most functions are named as `get_functionName` ( For example, the function `get_horizons_coord()` calculates the coordinates of celestial objects using the JPL Horizons system. Despite the calculation aspect, the name "get" was chosen to emphasize retrieving the result (I guess but IDK), abstracting away the computational steps involved )

While I agree that "compute" might feel better, I think we should use "get" when the focus is on what the user is obtaining rather than how it’s obtained. If the goal is to align with SunPy's established patterns and keep the naming intuitive for end users, "get" might just be the better name

**Comment by settwi** [comment]
Gotcha. So if this changed from “get” other things would also have to change? Hrm…

Re: absurd method names, the computation method is still included in the current implementation, just via a keyword instead of a separate method name. A less-absurd way to write it could be something like,

```py
from sunpy.map.contouring import compute

# assuming a Map m
contour = compute.using_contourpy(m)
...
```

I agree this is clunkier especially because it isn’t a Map method and is a free function instead.

In any event, if folks want to keep “get” then so be it. In code and writing in general, I have found that there is almost always a more precise verb than “get” which can be used to communicate the method intent and function more clearly.

**Comment by ayshih** [comment]
> Gotcha. So if this changed from “get” other things would also have to change? Hrm…

No, that's not a concern of mine.  The `get_*` functions most likely to be used by users are all in `sunpy.coordinates`, where parallelism with `astropy` API is a consideration.  Changing the name of this `Map` method wouldn't have any knock-on effects.
 
> Re: absurd method names, the computation method is still included in the current implementation, just via a keyword instead of a separate method name.

As a matter of history, the reason there's a selectable implementation is because we're continuing to support a deprecated implementation.

I'm fine with `find_contours()` as the new name, which makes it parallel with scikit-image (even though that happens to be the deprecated implementation).  If you like `find_contours()` more than `get_contours()`, create a PR, and I'll approve it.
